### ISSUE TITLE
Should keyword be somewhere in `@trigger`?

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1005]
We do call the tab where you set up a keyword triggers `Triggers` after all. Seems logical you could access what triggered the flow that way..

**Comment by rowanseymour** [comment]
Currently there's only `type` and `params` exposed on `@trigger` in expressions but I don't see any reason we couldn't expose other things for other trigger types. A keyword trigger in RP ends up being `msg` type trigger in goflow, and contains the msg and the match, e.g.

```
"msg": {
  "uuid": "2d611e17-fb22-457f-b802-b8f7ec5cda5b",
  "channel": {"uuid": "61602f3e-f603-4c70-8a8f-c477505bf4bf", "name": "Twilio"},
  "urn": "tel:+12065551212",
  "text": "hi there",
  "attachments": ["https://s3.amazon.com/mybucket/attachment.jpg"]
},
"keyword_match": {
  "type": "first_word",
  "keyword": "start"
},
```

So it would be straightforward to expose those in some way. Just have to remember that those fields won't exist for other trigger types (e.g. channel action).

**Comment by nicpottier** [comment]
So right now if you do `@trigger.type` on a keyword started trigger you would get `keyword_match`?

To this week's earlier tweak to make `params` always be present I wonder whether we should be sticking it in there and saying you should use `type` to figure out how you were called / interpret `params`?

Feels weird to now always have `params` but then have `msg` and `keyword_match` be siblings to that.

**Comment by rowanseymour** [comment]
Ok bear in mind I'm just talking about the internal representation of things here:

`type` is `msg|campaign|channel|flow_action|manual`

a `msg` trigger used use for a keyword match (it'll have a `keyword_match` field) and a catch all trigger (it doesn't have a `keyword_match` field)

a `campaign` trigger has an `event` field which includes the `campaign` and `uuid` of the event in RP

a `channel` trigger also has an `event` which includes the `channel` and type of channel event (e.g. `new_conversation`)

a `flow_action` trigger has a `run_summary` field which contains the summary of the run that triggered it - used to construct `@parent` in expressions 

all of the trigger types also have a `params` field but this is only currently used for `manual` triggers (`extra` from the API call) and `channel` triggers (`extra` from the channel event)

From the pov of expressions, not sure we need to bundle everything into `params`. For example for a `channel` trigger it might be useful to have `trigger.channel` and `trigger.params`

**Comment by nicpottier** [comment]
Thanks for the context. Let's start with what is most logical from the user's perspective though and work backwards from there.

Didn't we just make it so that `@triggers.params` is always present (just empty?)?

Isn't it weird to have that present on a keyword trigger then? Or maybe we reverse course there.

**Comment by rowanseymour** [comment]
Yeah to be clear I'm not saying the internal representation has to match what is exposed in expressions.

One difficulty here is that the editor can't know the type of the trigger when auto-completing, so that's certainly an argument for triggers being exposed with a consistent schema. And that means merging fields or using the superset of all fields.

So for example if we wanted to expose..

  * `msg` and `keyword` for `msg` triggers
  * `params` for manual triggers
  * `event` and `params` for channel triggers

Then we could define a scheme which is a the superset of those:

 * `trigger.msg` set for msg triggers, null for manual triggers
 * `trigger.keyword` set for msg triggers with keyword, empty for manual triggers, catch all triggers.
 * `trigger.params` empty dict for msg triggers, set for manual and channel triggers with `extra`
 * `trigger.event` set for channel triggers, otherwise null

or what _I think_ you're suggesting...

* for msg triggers 
  - `trigger.params.msg` the msg
  - `trigger.params.keyword` the keyword
* for manual triggers
  - `trigger.params` either `extra` passed by user or empty object
* for channel triggers
  - `trigger.params.event`
  - `trigger.params.event.channel`
  - `trigger.params.extra` either `extra` from event or empty object

But not sure how bundling everything into params helps cuz you're still stuck with the editor not knowing the schema of `params` and not being able to auto-complete things.

So I'd say the super-schema is easiest for users - the auto-complete can tell them what each field means.

**Comment by nicpottier** [comment]
Hrmm, ya.. the `params` case does get especially weird in the channel case where we have both `params` and `extra` which would be awful confusing.

I am a bit worried about having all these optional fields show up in the autocomplete but maybe that is the best of the worst? We can't know how a flow is called so I guess it is either that or no autocomplete at all on `trigger` and certainly the former is nicer for the user.

Also prefer not having a very deep hierarchy.

So ya, `trigger.keyword` etc.. does seem the best. I guess the related question is whether we still feel `params` always being an empty dict is still the right thing given that since we are saying all the other optional fields are `null`.

**Comment by rowanseymour** [comment]
Yeah it's definitely weird to have a bunch of fields which may or may not be set, but at least we can provide some explanation via 100 chars of help text as to why. `trigger` is the only thing in the context thus far with this property of being typed. `input` is similar in that it has `type` but we only have one type (`msg`) and I often wonder if we should ditch that and just say inputs are messages.

Re `params` always being non-null.. maybe there's an argument for it only being non-null for trigger types that can set it.. i.e. always non-null for manual triggers.. but I don't feel strongly. The other things are fixed structs so they can't be represented by `{}`, params is a BOD, so `{}` is a valid default.

**Comment by nicpottier** [comment]
I think from a consistency point of view ya I'd prefer it to be `null` in the case of triggers that don't use it and always a dict otherwise.. what do you think?

**Comment by rowanseymour** [comment]
Don't feel strongly. Will make it always non-null for `manual` and `channel` type triggers.

**Comment by nicpottier** [comment]
This is a param now on `@trigger` right @rowanseymour ?

**Comment by rowanseymour** [comment]
No seems I made the changes to `trigger.params` but never added `trigger.keyword`. Added https://github.com/nyaruka/goflow/issues/786

**Comment by nicpottier** [comment]
Just a note for future me that present me just found himself finding it not entirely intuitive that `keyword` isn't in `params` after not thinking about this for 9 months.
