### ISSUE TITLE
Npm security issues

### ISSUE THREAD

**Issue by pangoSE** [rapidpro/rapidpro#1013]
NPM reported lots of serious security issues when running 
$ npm install

**Comment by ericnewcomer** [comment]
Thanks for the report, it'd be especially helpful if you provide as much detail as possible so that when we look into it we can make sure we are looking at the same thing when reproducing it.

**Comment by pangoSE** [comment]
Were you able to reproduce?
I don't know how to increase the verboseness of npm but it complained about bower and suggested webpack instead. 
I presume if you fire up an empty server (Ubuntu 18.04 I used), install the newest npm and run the command above you will see the same.

**Comment by pangoSE** [comment]
It suggested to run npm audit which presumably gives a lot more details about the issues.

**Comment by ericnewcomer** [comment]
I’m not disagreeing there are things to be addressed, npm security warnings constantly pop up. Just trying to address the actual report. Bower being end of lifed is an issue. Certainly npm audit warnings are another. A good bug report is specific so that we can be sure we are talking about the same thing. I’m aware of some of these, but I can’t really speak to the status without knowing what specifically the report is about. 

If the output of npm audit is the concern, then include the relevant bits so when it is repro’d we can be sure we are seeing the same thing. 

Thanks!

**Comment by pangoSE** [comment]
Hi. Here is the output as requested
the output is a little garbaged by the pipe to a file but it is understandable enough.
257 high security vulnerabilities ready to be fixed
