### ISSUE TITLE
Add constraints on flows_flowsession state

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1015]
Just wondering whether maybe we should have a DB constraint saying that a session can't have `ended_on` be set and a status of `W`. (and maybe vice versa)

**Comment by rowanseymour** [comment]
I like this - we have some similar constraints on msgs

**Comment by rowanseymour** [comment]
Also could limit the allowed changes to `status` to just...

```
W -> (C | I | X | F)
```

And do the same for `flows_flowrun.status`...

```
A -> (W | C | I | X | F)
W -> (A | C | I | X | F)
```

I remember when we added similar constraints on `msgs_msg` the only casualty was had to rewrite some unit tests that were doing hacky things with msgs.. but that's for the best.

**Comment by nicpottier** [comment]
Ya, those tie our hands a little bit in case we need to manually futz with things but generally agree that's a good idea.

**Comment by rowanseymour** [comment]
Had a little think about this if we want to do DB level validation more generally. There are two types of things we might want to validate:

- Value changes: these would have to implemented as SQL `TRIGGER` + `FUNCTION`.. because you have to know before and after state.
- Absolute values: these could be implemented as SQL `ADD CONSTRAINT`, and as of Django 2.2.. you can let the Django model manage these https://docs.djangoproject.com/en/2.2/ref/models/constraints/

With the latter it becomes easy to do checks on fields that take a set of choices, e.g.

```python
class Meta:
    constraints = [
        models.CheckConstraint(check=Q(status__in=('S', 'F')), name='status_choices')
    ]
```

Which results in...

```SQL
ALTER TABLE "airtime_airtimetransfer" ADD CONSTRAINT "status_choices" CHECK ("status" IN ('S', 'F'));
```

Tho my best attempt to make this more generic looked like..

```python
def choices_constraint(field_name, choices):
    return models.CheckConstraint(
        check=Q(**{f'{field_name}__in': [c[0] for c in choices]}),
        name=f'{field_name}_choices'
    )


class AirtimeTransfer(models.Model):
    STATUS_SUCCESS = "S"
    STATUS_FAILED = "F"
    STATUS_CHOICES = ((STATUS_SUCCESS, "Success"), (STATUS_FAILED, "Failed"))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    class Meta:
        pass

    Meta.constraints = [
        choices_constraint("status", STATUS_CHOICES)
    ]
```

Because inside `Meta` you can't see things on the outer class.

**Comment by rowanseymour** [comment]
Recently added a trigger to prevent illegal state changes
