### ISSUE TITLE
Flow globals

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1017]
![photo_2019-08-14 18 09 23](https://user-images.githubusercontent.com/6073075/63094439-cb3a8b80-bf3e-11e9-892e-962f781cd973.jpeg)

That's the User Story Mapping for Flow Parameters capability in RapidPro. This functionality aggregates the following values to the product:

- Similarly to Contact Fields, it creates a space to save data globally and access it inside flows.
- Flexibility to replicate flows in different workspaces. For example, a standard Registration flow that just changes the name of the country (`Country Name` would be the parameter) in some specific parts of the flow.
- Setup common values that are shared in different flows and once they are changed, it applies in all use cases. For example, a webhook call that is made in many different flows but uses the same Authorization token that can be changed over time.

## User Activities

There are three main activities:

1. **Add Flow Parameters**: Simply setup flow parameters with key and value to start using it in flows.

2. **Use Parameters**: Uses flow parameters as variables and as a rule to split by.

3. **Interact over API**: Simple management of flow parameters over API, which gives dynamism to it allowing to update values when necessary according to external conditions. 

## Steps and Details

The idea here is to detail and prototype each activity to get your approval and move forward with the coding phase.

### List Flow Parameters

Very similarly to Contact Fields, we would have a `Manage Parameters` button in Flows page:

<img width="844" alt="flows_fields" src="https://user-images.githubusercontent.com/6073075/63094394-a47c5500-bf3e-11e9-8437-b0b367580cd5.png">

Once they click on this button, the list of Flow Parameters will be available displaying its usage in flows:

![manage_params](https://user-images.githubusercontent.com/6073075/63094401-a9d99f80-bf3e-11e9-9f50-fa0b5509c2dc.png)

It will be sorted alphabetically and it's also possible to search by keys in the same way as Contact Fields allows.

#### Setup Key and Value

When clicking on `Create Parameter` the modal will open to setup key and value:

![setup_key_value](https://user-images.githubusercontent.com/6073075/63094405-ae9e5380-bf3e-11e9-8d57-46d345d10c42.png)

**Block Duplicates**: Avoid flow parameters with the same key.

### Edit/Delete Flow Parameters

Similarly to Contact Fields the modal to edit an individual parameter is the same the one used to create with a button to delete it.

### Use Parameters in Flows

**Call as Flow variables:** The suggested way to do so is by using the `@param.key` format.

**Split by Flow Parameters:** It's also useful for users, similarly to Contact Fields to split by using Flow Parameters.

### Interact over API

**GET:** A simple GET request to retrieve all key and values configured or filtering by key.

**POST:** POST request to create or edit values of flow parameters.

--------

Let me know your thoughts on this. This is a feature that's part of [Push](https://github.com/udomobi/push) and is one of the features that we're adding to the main RapidPro to deprecate the previous one.

**Comment by nicpottier** [comment]
Just a note would be great if you started these off with a simple issue and everybody in the community could brainstorm together online instead of these big dumps all at once.

This is something we've talked quite a bit about though in fairness I can't find a related issue either. :) We tend to call these Org Fields, not Flow Fields / Parameters because they can be used outside a flow, IE when sending a broadcast message, in a campaign message etc..

One thing which I think is right in your proposal but worth calling out specifically is that these are read-only from a flow perspective, IE, you can't be incrementing one of these values in a flow. Updating a global field has been an ask we hear now and then and it carries with it a million complications around race/locking during flow execution. We've even talked about a basic redis like API that would allow for some basic permutations there that wouldn't require locking. That said, I don't think we really want that and most of the gains are in having something you can just access.

Another which is worth calling out is that these aren't typed. I *think* that's right, but we should discuss that and make that decision explicitly. Are we losing anything by not having any typing / casting done? I can't really think of any big downsides there, if it looks like a date or location it will be able to be used in that way anyways.

We'll need some kind of limit on # of constants allowed on an org.. maybe 255 is good there but can be configurable via settings. That's the only real performance constraint I can think of.

Are these localizable? My intuition would be not, that these are a different thing, but again we should make that decision explicitly.

I think implementation-wise the path forward on this is pretty clear apart from some bike-shedding around names / flow variables names, placement in the UI etc.. I think `flow parameter` kind of collides with `@trigger.params` and implies that these are tied to flows, while they are really org level instead. That said, engine doesn't really know anything about orgs and maybe we want to drive home the point that these are constants in flows so maybe something like `@consts` or `@constants`? Or if we want to leave the door open to updating these in some future where we are smarter `@globals`?

Location of where these live in the UI is likely another question. There's a lot to be said for accessing them from the flow page as that is the most likely place they will be used even though they span more than just flows. That likely will fall out once we come up with a good name.

@rapidpro/nyaruka thoughts?

**Comment by rowanseymour** [comment]
I think it's important to clearly describe some usecases we're trying to support here so there's a clear distinction between related but different usecases (e.g. updating a global count, bulk localization in flows). You guys have clearly put some thought into this so I assume you have some real-world usecases in mind?

I think what we're trying to address here is something like..

* U-Report country offices share the same registration flows but each country office needs to change the country name and a website URL in the flows.

A related question to whether these are typed things, is whether they are excellent templates. If a user had a webhook URL like `http://example.com/stats.php?c=@contact.uuid`, would that be saveable and evaluatable as a global thing? If that were the case then `@const` and `@global` start to sound a bit misleading since they would have different values in different contexts... my gut feeling says we shouldn't allow that.

Also typing is something we can add later if the need arises. We just start simple by having expressions always treat these as TEXT type things.

And I guess I feel the same about localization. 1) if these are constants then they should be constants. 2) we could add it later if it started to make sense.

**Comment by nicpottier** [comment]
I hadn't thought of them being templates themselves.. I guess in your example above I would expect the flow to do something like `@globals.site_url?c=@contact.uuid`

Perhaps with the mindset of improvement later `template` could be a type on these in the future and those then get evaluated. (and everything before is just `text`)

**Comment by ericnewcomer** [comment]
I think `@globals` makes sense because it allows flexibility going forward if we want to evolve this. 

One thing worth mentioning to make sure we cover all the bases, and it is sort of alluded to in the screenshots but not called out explicitly, is that these would need to be dependencies on flows. This also requires updates to the reference identification by goflow, creation on flow import, gating flow deletion, etc. 

As with most new features, I agree it’s best to make as few promises as possible to start. They should be constants in every sense to begin with and we can look at augmenting with additional dynamism if demand calls for it.

**Comment by johncordeiro** [comment]
Yeah, it would be great to discuss these things together and building the user map for each feature.

----------

### Use cases

That's exactly what @rowanseymour has exposed. I want to enable users who access multiple workspaces to create template flows that can be shared and customized by using parameters, the country name and website URL are perfect examples. We can build a full program based on template flows and replicate them in different workspaces just updating parameters.

One other use case that I can share is, for example, is a flow that we've built to search about location info by country or city names, and I'm using a [Geonames API](http://www.geonames.org/export/web-services.html) that requires an Authentication token, instead of putting my key in the flow I'll put a parameter as the Webhook header and I'll share that with other colleagues that use RapidPro.

### Org vs Flows

Flows are exportable and shareable pieces of RapidPro, they can be just templates and we could easily have a Marketplace for them. Because of that, I believe that's reasonable to restrict the usage of parameters just in Flows and not in broadcasts or campaign messages.

### Read-only

I agree that we should start with the read-only approach, but with a name that allows the write-mode in the future, and here's the start point to discuss the name. 

### About the name

I don't believe that `@trigger.params` collides with `@params`, actually I feel that they confirm one another, once they are parameters in different contexts. However, if we find a name that refers to a value that in the future would allow read/write, it's not a bad idea. I can't think of anything different 😄 

### Localizing and Typing

For now, it doesn't make too many sense to localize nor typify these values, in this point I believe all agree, it's something that can be added in the future if necessary.

### 255 Limit

The limit for 255 parameters sounds very standard and I totally agree.

**Comment by nicpottier** [comment]
Great, auth tokens are definitely another great example for these. Thanks for that.

From a user's perspective I think it would be a bit confusing if we had variables that weren't available in broadcasts or campaigns (which are actually flows under the covers) but available in flows. To be clear that is already the case to some extent, but that is for things like `run` and `parent` etc, which are intrinsically tied to flows. There is nothing here that is really tied to flows, these are just "constants" that are a level above flows.

The issue I take with `params` is that that sounds a lot like something that is specific to a flow run. IE, you are starting this flow with these params. It is somewhat hard to get out of the programmer mindset so hard for me to think whether `@globals` or `@constants` is any more or less obvious, but at least it is more correct in the programming sense.

Another way to think about these is that they are variables on the environment the flow is running in. IE, they are analog to environment variables in a shell context. So maybe something `@env.params.foo` or `@env.foo` could make sense? Not sure how many users know about environment variables either but perhaps that is the easiest analog?

**Comment by nicpottier** [comment]
> One thing worth mentioning to make sure we cover all the bases, and it is sort of alluded to in the screenshots but not called out explicitly, is that these would need to be dependencies on flows. This also requires updates to the reference identification by goflow, creation on flow import, gating flow deletion, etc.

Hrmm, ya, good catch. There are dependencies like flow fields, in that during an export/import cycle we can recreate these without problem, but yes, we will want to prevent deletion or renaming of these if currently being used and create them dynamically on imports if they do not already exist on an org. (the flow may not function correctly in that case, but the user should be able to browse / see these as being unset)

I guess that is also something worth calling out explicitly. That we do not export these values during export. We export them as dependencies / references, but we don't want people leaking auth tokens or the like in their flow defs by including "defaults" when exporting a flow that may use these.

**Comment by johncordeiro** [comment]
In this case, I vote for `@globals` and we move the management of `Global Values` to the organization home page, that after clicking on it, a different page is opened with the same usability exposed in the very first screenshots.

**Comment by rowanseymour** [comment]
I do wonder if `Global Values` is something that makes more sense to programmers than our typical customers. Might be clearer to call them `Flow Parameters` or `Flow Fields` or `Flow Variables` in the UI since that clarifies that these are things which are for _customizing flows_.

I also like the idea of an analog with environment variables..

Wonder if we'd want to expose other things that are on the `env` in goflow? There's stuff there like language, timezone, date formats that could be useful in more advanced flows? In which case we could nest variables like...

```
env.variables.country_name
env.variables.auth_token
env.timezone
env.date_format
```

**Comment by nicpottier** [comment]
To my earlier point they aren't just available in flows though are they? Broadcasts and campaigns would access these no?

I feel like Environment Variables is the closest thing to what this is but question there is just how intuitive that is. Also, would much prefer `env.fields` over `env.variables` because then we'd be consistent with contact fields at least. (IE, field over variable or parameter)

As for exposing envirnoment, `timezone` will be moving to be a contact specific field before long, so that won't be there. Date format is a bit goofy of a thing for someone to access but maybe that makes sense if you are building a reusable flow? But you could imagine `env.name` being the org name and that seems kinda useful.

**Comment by rowanseymour** [comment]
Fair point about their use in broadcasts. Well if they're accessed via `@env` maybe they need to be called `Environment <Somethings>`

I would argue that it's actually clearer if the naming is distinct from contact fields. All these bags of values (contact fields, run results, trigger params) are often referred to without context (e.g. `@fields` and `@results`) so it's actually better to pick a new noun like `variables`.

Timezone will be added to contacts but it will still exist in the `env` the same as `language` currently does - we always need a default.

But having said that.. I could probably be persuaded that there's nothing really useful on the excellent environment that we need to expose. `env.name` is neat.. but you could just add a custom value for that. In which case we get the simplicity of `@env.foo` and we don't even need to agree on a second word!

**Comment by ericnewcomer** [comment]
I think them starting as constants makes `@variables` not great and them possibly becoming mutable at some point makes `@params` not great (same reason stuffing them in `@env` feels a little weird to me). Of all the options we've mentioned, `@globals` is i think the only one that works best in both cases. Second choice in my mind is `variables` (or even `Global Variables`) since it is distinct from other things in the system and is probably the easiest one to grok what it is, just looking past that they have to edit them in the UI for them to vary. But ya, don't need to bike shed the name. 

@johncordeiro I like the auth token example too, makes a lot of sense. I do think these things whatever they are called should be available in broadcasts and campaigns since there is no reason they need to be restricted to flows (though we need to consider dependency implications there as well).

**Comment by nicpottier** [comment]
Another possible use case here that I'll just note, but doesn't need supporting is the management of a lookup table. We often see people wanting to loop up a record from a fairly static set based on some key or the like. Right now we tend to point them to airtable but maybe having table like support in `globals` could makes sense in a feature creep world?

Ok, we need to just settle on naming already.

Can anybody not live with `@globals`?

**Comment by rowanseymour** [comment]
`@globals` it is then

**Comment by rowanseymour** [comment]
also wouldn't be anything stopping users from stuffing JSON in there and calling `json_parse` on it

**Comment by nicpottier** [comment]
@johncordeiro if you are in agreement, how about your team tackles the Django side of things and we'll take care of the rest?

Seems it would be a matter of creating a `globals` django app, associated models and the management views for that. Once you have that to a point where it works you can submit a PR and we can take care of the editor/flow engine side of things which shouldn't take long.

**Comment by johncordeiro** [comment]
Let's move with `globals`, PR coming soon. Thanks for your collaboration.

**Comment by chris-erickson** [comment]
I can't recall if this was discussed, but editing these via flow would be wild.  We have campaigns where we might send the same data to a lot of users.  If we could run a flow ahead of the campaign running and could populate this, it would save us from what we sometimes do by calling a web hook for each user (it would return the same data for all users so it's redundant).

Right now we have some caching mechanisms to ease the pain, but it still has all the overhead of a webhook (server infra, writing out the web hook logs, etc etc).

**Comment by rowanseymour** [comment]
@chris-erickson the plan is to introduce these as read-only initially, but then explore whether it makes sense to make these writable in flows, or introduce a different concept for writable global state. Obviously writable global state has the potential to introduce weirdness like race conditions if not done correctly.

**Comment by nicpottier** [comment]
Done.
