### ISSUE TITLE
Rethink workspace home page to improve discoverability of integrations

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1063]
Maybe two tabs on that page? Or make integrations its own page?

Integrations would be a list of:

- Channels
- Classifiers
- DTOne
- Chatbase
- Other third party services we add in future

**Add Channel** and **Add Classifier** would get their own big blue buttons - right now these are somewhat hidden in the gear menu.

Would be helpful for orgs with a lot of channels - right now the main org settings get punted to the bottom of the page.

**Comment by nicpottier** [comment]
We don't really have tabs anywhere, but ya, maybe an "integrations" page makes sense in addition to the current account page. Perhaps that is a tab that always sticks around instead of the channel circle that disappears once you you add one?

Agree that classifiers especially are hidden right now. Majority of accounts only add a single channel so our setup there isn't too bad I don't think. But airtime and chatbase (and resthooks?) are probably good candidates to have their own home.
