### ISSUE TITLE
Consistent naming restrictions

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1105]
Things like labels, groups, fields, flows (and soon globals) all have rules about what is a valid name.. seems like we could consolidate those for simplicity.

**Flows**, **Campaigns**

No restrictions! I just created a flow called `$^@!!!!`

**Fields**, **Globals (?)**

```python
def is_valid_label(cls, label):
    label = label.strip()
    return regex.match(r"^[A-Za-z0-9\- ]+$", label, regex.V0) and len(label) <= cls.MAX_LABEL_LEN
```

**Groups**, **Labels**

```python
@classmethod
def is_valid_name(cls, name):
    # don't allow empty strings, blanks, initial or trailing whitespace
    if not name or name.strip() != name:
        return False

    if len(name) > cls.MAX_NAME_LEN:
        return False

    # first character must be a word char
    return regex.match(r"\w", name[0], flags=regex.UNICODE)
```

**Comment by nicpottier** [comment]
Does seem like groups and fields should have consistent naming restrictions, mostly because they are likely to be used in similar contexts. (IE, contact searches or expressions)

Thus far flows and labels aren't used in those kinds of contexts at all, but I don't see any reason why we should have a different answer there. All having the same restriction seems logical to me.

And that restriction should probably be the same as groups I would think. (anything that starts with at least one word character)

**Comment by rowanseymour** [comment]
Update: anything with a `name` now follows the same rules for validating that.. except fields and globals as they have the additional requirement of needing a `key` which is valid in expressions. It gets pretty confusing right now when you add a field because the name entered can produce a key which is a duplicate, but we don't display auto generated key in the UI.
