### ISSUE TITLE
relayer param in POST messages API call not working

### ISSUE THREAD

**Issue by rgaudin** [rapidpro/rapidpro#111]
When sending a message using the API `POST /api/v1/messages.json`, we can specify a `relayer` to send the message from.

When specifying a relayer (`int`), **neither the specified relayer nor the associated relayer for that contact (if exist) is used** but instead the default relayer is used.

Consequences:
* `relayer` parameter is not working properly
* it sets the *associated relayer* of the contact to that default relayer
* It is inconsistent with not specifying the `relayer` parameter at all (which sends to the associated relayer)

**Comment by nicpottier** [comment]
Looking at the code this does look like it wouldn't work:
  https://github.com/rapidpro/rapidpro/blob/master/temba/api/serializers.py#L1113

We don't actually have a mechanism for Broadcasts to force a particular Channel, so this will be an expensive (but necessary) fix. I'm very surprised about the behavior of preferred channel be overwritten though, that we'll have to dig into further.

I'll look at this Monday and try to get a fix out by EOD, it will be a large database migration to add channel to broadcast though.

**Comment by rgaudin** [comment]
ahhhhhh
Looking at the code, I see that it expects a `channel` param and not a `relayer` one.
I tested and it works as expected using `channel`.
It's a documentation issue then !!

Thanks @nicpottier

**Comment by nicpottier** [comment]
@rowanseymour I still don't think we are quite doing the right thing here, would you agree?

To me it looks like we are actually rewriting the preferred channel for the URN at: 
  https://github.com/rapidpro/rapidpro/blob/master/temba/contacts/models.py#L395

Which doesn't strike me as quite right. Not sure what the use case is there, but it seems to violate our rule about only resetting preferred channels on incoming messages.

Seems the more correct way to do this is to have a Channel parameter on Broadcast that then forces the channel on the SMS when creating the sub-messages.

Thoughts?

**Comment by rowanseymour** [comment]
I've just finished a PR for a new broadcasts endpoint for sending messages. There I haven't included a channel parameter because I was thinking that didn't make sense in this brave new world of different URN schemes. To normalize incoming tel URNs, the endpoint looks up the orgs default SEND channel for tel URNs.

Also not sure about adding a single channel to `Broadcast` (`Broadcast.preferred_channel` ?) that would be only be relevant for one particular scheme. Suppose a contact has a tel URN and a twitter URN with a higher priority. If the user specifies a tel channel when sending, should that override the contact's URN priorities?

The "correct" solution might be to let the user provide a map of schemes and preferred channels... but that sounds a lot more complex than anything we want to add to `Broadcast`.

Regardless of all that, seems we should make sure that calls to `Contact.get_or_create(..)` only pass in channel in the context of incoming message handling. Maybe rename that var for clarity.

**Comment by nicpottier** [comment]
@rgaudin Maybe you can tell us more about the use case you have for passing in the Channel parameter?

I'm guessing the use case has to do with having a cheap(er) way of sending outgoing messages and wanting to force that channel for large blasts.

**Comment by rgaudin** [comment]
Exactly.
In our situation though, it's not a preference to specify the outgoing channel but mandatory.
Our channels are both limited to their own network and messages targeting a different network just fails.

We're using those no-incoming-message outgoing broadcast to send *invitations* to our friends.
We created an Android app that dumps our (the local u-report team) address book numbers and we send them all invitations later.
All in all, we've already collected (and sent-to) about 15K unique numbers using this method.

**Comment by rowanseymour** [comment]
So I assume you take those numbers, sort them by network outside of RapidPro, and make a blast for each network specifying a channel for that network?

Currently we don't pass a channel to `Broadcast` so this is only working because `Contact.get_or_create(...)` is "incorrectly" setting the preferred channel of new contacts, that is then picked up when `Broadcast.send` is calculating which relayer to use for each contact.

If we added channel(s) to `Broadcast` then it could mean a few different things in the context of sending to specific URNs and sending to contacts with multiple URNs. For example it could mean...

 1. A single forced channel
      * if a recipient URN has a different scheme to that channel, then it's an error
      * if a recipient contact doesn't have a URN with the same scheme, it's an error
 2. A single preferred channel
      * if a recipient URN has a matching scheme, use that channel, otherwise continue to calculate best
      * if a recipient contact's highest priority URN has same scheme as channel, use channel
 3. A single preferred channel and implicitly preferred scheme 
      * if a recipient URN has a matching scheme, use that channel, otherwise continue to calculate best channel
      * if a recipient contact has a URN with that channel's scheme, use that URN with the preferred channel
 4. Multiple channels ....

I wonder if the best solution here might be to limit the use of `channel` to only apply to URNs passed to the endpoint? That would cover this specific use case, whilst not making the channel selection logic for contacts more complicated than it already is.

**Comment by nicpottier** [comment]
I think 1) is the most obvious, and fits this use case most obviously. I'm not positive we need to throw errors either, rather just ignoring URNs or Contacts that are unreachable by a forced channel.

Even if we limited channel to only work on URNs, we'll still need to add Channel to broadcast, as we do not want to be resetting the preferred Channel on URNs when sending outgoing messages.

So to me it seems we need to:

1. Add channel to broadcast, use this as the forced channel to send messages out to. If there is no matching URN for the scheme of the forced channel for a particular contact, then that contact is ignored.

2. Change ```get_or_create``` to not clobber in the outgoing case. (or just audit it's use to only be used for incoming cases.

3. Modify API calls to create broadcasts using the forced channel.

Sound ok?

**Comment by rowanseymour** [comment]
Agreed on #1. I don't think we'd throw exceptions for non-matching URNs and contacts, and we already ignore contacts that we can't find a sendable URN for. Maybe one day that sort of thing will go into a user-viewable event log.

I think for your point 2, there's no way for `Contact.get_or_create` to know in what context it's being called so we'll have to audit calls to it. If we rename `channel` to something like `preferred_channel` then that should make it clearer when and when not to provide that.

**Comment by rowanseymour** [comment]
I can add changes discussed above to https://github.com/nyaruka/rapidpro/pull/16

**Comment by nicpottier** [comment]
Great, also I guess we need to fix the docs for api/msg to use ```channel``` instead of ```relayer```

**Comment by nicpottier** [comment]
@rgaudin Note that this is live now. (the /broadcasts API endpoint)

**Comment by rgaudin** [comment]
Great. I'll adapt our code once the documentation is updated.
