### ISSUE TITLE
Copy and paste flow steps

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#112]
Sometimes a step (such as a multiple choice selection, for example) may be repeated within a flow. Would be nice to be able to copy and paste flow steps/actions within a flow.

**Comment by nicpottier** [comment]
This has come up a few times and I definitely don't disagree. Apart from implementation challenges, we've always kind of wondered whether it is a sign that we need another kind of construct instead of enabling ever larger flows, so that's been the main reason it hasn't been a big focus.

**Comment by ewheeler** [comment]
good point. any ideas of constructs for larger flows? 
i've been asked about this several times as well. so good to get it recorded here for further discussion

**Comment by litlfred** [comment]
Currently a flow can kick off another flow, but cannot return to the
originating flow.

It seems to me that if you can allow for an option to return to an
originating flow and allow surfacing of (some or all)data collected in the
called flow to the calling flow, you would be in a good position to build
large flows off of smaller ones in a procedural way.

This would also let me implement a specific request I have had.

Cheers,
-carl

**Comment by nicpottier** [comment]
Ya, using flows as "functions" is another approach. I think that is a tough one for users to wrap their head around though.

Yet another option we've talked about is to allow stacked rulesets, that is instead of forcing a ruleset to always be followed by an actionset (ie, parse response, send reply, parse response), instead allow the user to have multiple rulesets in a row.

This allows for more complicated logic (essentially ANDing across variables) and might also address some cases where people are trying to do looping.

All of these are a lot of extra rope for users and it is hard to take rope away once you give it, so we've been pretty cautious about adding any of them, but stacked rulesets is probably our favorite at this point.

**Comment by ericnewcomer** [comment]
Just to keep this conversation current, we do now support rulesets to rulesets and actionsets pointing to actionsets. Not sure that totally addresses the issues raised at the beginning of this thread, so leaving it open. Flows as subroutines is something we've since added to the roadmap, but we don't have a timeframe for.

**Comment by nicpottier** [comment]
Now that we have subflows that can return, I would say copy/paste is an anti-pattern.
