### ISSUE TITLE
Making custom contact field type reqs clearer for users

### ISSUE THREAD

**Issue by LeahBreedenNyaruka** [rapidpro/rapidpro#1134]
Confusing for users when creating new custom contact fields for use in campaign events. Must manually change field type to `date & time` on the Manage Fields page, but this is not made clear.

**Comment by nicpottier** [comment]
You figured it out!  :)

Some ideas:

1. When a field is created in a flow should we ask what type the user wants it to be? The root of the problem here is that that automagic field creation is assuming the user wants a text field.

2. Alternatively we could try to infer the type for the datetime case, I would guess most of the time people are doing this they are setting the field value to `@(NOW())`, we could detect that and create the field as a datetime in those cases.

3. Another approach would be changing the campaign event editing dialog to show all fields but if you click on a non-date field we tell you you can't use it because it isn't a datetime and give you the option of changing it right then and there with a button click.

Any others? @ericnewcomer @rowanseymour @norkans7

**Comment by rowanseymour** [comment]
Not in love with 2. but I actually think 1. and 3. both sound pretty reasonable. 

For 1. can we have modals on top of modals? Once you press enter to create the new field you get a confirmation with the name/key/type (changeable). I like this because it makes it clearer to the user that we're actually creating a new contact field here.

**Comment by ericnewcomer** [comment]
Feel like three has the least amount of friction and is the easiest to implement. Only downside there to me is that list being muddied with a bunch of non datetime fields. Maybe it starts as datetime only with an option to expand to all?
