### ISSUE TITLE
Empty data retrieve on contact search (Bengali)

### ISSUE THREAD

**Issue by pericles-jr** [rapidpro/rapidpro#1144]
Hello guys,

I've facing a great problem while using Bengali language on RapidPro, it can't search for any contact field that stores data using that language.
For example it returns no result if you try to search for a district filtering by its name: district="BENGALI_LANG"

Would you mind pointing me in the correct direction to solve this problem?

Thanks in advance.

**Comment by nicpottier** [comment]
I take it you have rp-indexer doing the right thing along with
ElasticSearch.

There shouldn't be any issue searching for districts but note that your
search needs to be whatever name is used for that district as the primary
name, not any alias. IE, whatever name shows up as that contact's value.
And if your field is set to "District" then note that the value there must
match whatever administrative boundaries you have imported.

All that to say, as far as we know there are no issues with unicode names,
so I suspect your issue is either that that district name is not considered
valid (and therefore not being set as a district value on the contact) or
you are searching for an alias as opposed to the canonical name for that
district.

Cheers,

Nic

**Comment by rowanseymour** [comment]
Closing for now pending more information
