### ISSUE TITLE
add CORS settings to the project

### ISSUE THREAD

**Issue by hudsonbrendon** [rapidpro/rapidpro#1156]
I recently had a problem with CORS, I noticed that it is not configured in the project and that it would be interesting to implement it using a lib https://pypi.org/project/django-cors-headers ? Do you agree with the proposal?

**Comment by rowanseymour** [comment]
Is this for making API calls? We've generally discouraged people from writing frontends that call the RapidPro API directly because we don't want them sharing their API tokens in frontend code.

If someone has a good usecase for this and it can be added in a way that is optional for different deployments then I think we'd accept a PR.

**Comment by rowanseymour** [comment]
Closing for now but can reopen with more information
