### ISSUE TITLE
Move Contact modifications to RapidPro

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1161]
We've moved searching to RapidPro:
  https://github.com/rapidpro/rapidpro/issues/1085

But we still evaluate per-contact queries when updating contacts via the UI or API. We now have an endpoint on Mailroom to do this instead which takes care of campaign updates and dynamic group updates, we should move all contact updates on the RapidPro side to use that instead.

Places that need to be migrated over:

- [x] contact create from UI: name and tel
- [x] contact update from UI: name, language, urns, groups
- [x] contact update from UI: fields
- [x] contact list page: block, unblock, stop
- [x] contact list page: change group memberships
- [x] contact create from API
- [x] contact update from API: name, language, urns, fields, groups
- [x] contact bulk actions API: groups, block, unblock
- [x] contact import

**Comment by norkans7** [comment]
I started on this in https://github.com/nyaruka/rapidpro/pull/2751

 However it seems to me that we need to make goflow know about `Contact.is_blocked` so that the modifiers can be used and make sure the we will not add to groups blocked contacts

Currently RapidPro does 
https://github.com/nyaruka/rapidpro/blob/9c172d971499b8475fdece2a891e1446f1beafce/temba/contacts/models.py#L2711

GoFlow is not aware of is_blocked
https://github.com/nyaruka/goflow/blob/f7c199646489dbf5595deb37ae5834056875acc9/flows/actions/modifiers/groups.go#L48

Similarly should we use modifiers to stop contacts instead of https://github.com/nyaruka/mailroom/blob/0dbf670a160445f990b9f91ffe9ac9dd7eea84f6/models/contacts.go#L861 ?

**Comment by rowanseymour** [comment]
In theory I think it would be fine for goflow to know about stopped and blocked states - we could allow flows for stopped and blocked contacts as long as they don't send messages. Give people triggers for when contacts stop.

Tho it's probably ok as well just to have mailroom ignore an add-to-group modifier when it sees the contact is blocked or stopped, no?

**Comment by nicpottier** [comment]
I think it is more that we need some way of describing the user blocking a contact. Since the end goal is to get all contact modifications happening through this endpoint, we need some way of representing that action which doesn't currently exist. It doesn't necessarily need to exist in the flow world as an action. (blocking specifically probably should but stopping is an interesting one here as that is initiated by the contact, not the user, the event often comes in from Courier actually)

Maybe another idea would be to have some modifier be implemented by Mailroom and not be part of Goflow? But then it would be adding in its own events etc as well.

I think I'd probably vote for both Blocking and Stopping existing as Events and Modifiers in goflow, but only Stopping being an action.

**Comment by rowanseymour** [comment]
With imports and contact creation moved to mailroom, this is done!
