### ISSUE TITLE
Bad request on telegram incoming messages webhook

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1168]
We've noticed that Telegram after some event (that wasn't identified yet) starts getting `Bad Request` from RapidPro in all the incoming messages, what is very strange is that when you switch the webhook to a new RapidPro channel, telegram resend all the errored requests starts working.

Did someone had this problem?

**Comment by nicpottier** [comment]
You are saying Courier starts returning a "Bad Request" to incoming HTTP requests from Telegram? Or that it is reaching out to Telegram and getting a bad request in that case?

For the latter, we did at one point see that given slow hosts you can get yourself in a state where all HTTP connections are being used up to a host, that was tweaked a while back here:
  https://github.com/nyaruka/courier/commit/714bd9339cca4dd077a2eabd678293f42dfc733a

And that seemed to address it for us. What version of Courier are you on? Obviously the more details the better here.

**Comment by johncordeiro** [comment]
it's the first case, incoming HTTP requests from Telegram after some point starts receiving Bad Request from courier.  We're in version 5.3.8 of courier.

**Comment by nicpottier** [comment]
Hrmm..we haven't seen that. Is it writing a channel log in those cases? Do other channel endpoints work? All I could think of is that for some reason Courier is out of file descriptors or something which would be from leaving some files open but that would affect all channels, not just a WhatsApp one I don't think.

**Comment by koallann** [comment]
Hey guys, I bring more news about it!

So we've notice that incoming HTTP requests from Telegram gets `400 Bad Request` with `"error retrieving media"` ([telegram.go#L121](https://github.com/nyaruka/courier/blob/master/handlers/telegram/telegram.go#L121)) because the request to retrieve file ([telegram.go#L287](https://github.com/nyaruka/courier/blob/master/handlers/telegram/telegram.go#L287)) returns `400 Bad Request` with the following body:
```json
{
    "ok": false,
    "error_code": 400,
    "description": "Bad Request: invalid file id"
}
```
I don't have more details about this file id error, but I think the question is whether a request error should be returned when a file cannot be retrieved because messages will be blocked in the Telegram webhook queue untill receives a `200 OK`.

To reproduce a incoming messages blocking just send a midia with size > 20MB to your bot, which is the limit:
> Maximum file size to download is 20 MB

https://core.telegram.org/bots/api#file

@nicpottier should we proceed creating message (if has text of course) even not be possible retrieving file?

**Comment by koallann** [comment]
https://github.com/nyaruka/courier/blob/master/handlers/telegram/telegram.go#L120
```golang
...
// we had an error downloading media
if err != nil {
    return nil, handlers.WriteAndLogRequestError(ctx, h, channel, w, r, errors.WrapPrefix(err, "error retrieving media", 0))
}
...
```

**Comment by nicpottier** [comment]
Hrmm, ya, so basically Telegram starts not delivering messages when we return an error, and we return an error when we try to download a file that Telegram deems too big.

If that is really the behavior then ya, seems we should return a 200 with a log that we ignored the message. (I think there's a method for writing ignored responses)

In the case where there is text I think creating the message is the right thing but we may want to annotate that log with something about ignoring the image because the file_id returned an error. (could be an independent channellog I suppose)

**Comment by koallann** [comment]
Ok! Thanks @nicpottier, PR coming soon.

**Comment by koallann** [comment]
Update: this behavior occurs indefinitely, but Telegram will continue to try to send failed messages anyway, we detected this in a high volume data exchange.

**Comment by johncordeiro** [comment]
Closing the issue once the hotfix was merged.
