### ISSUE TITLE
Flow Expiration Options

### ISSUE THREAD

**Issue by paradoxxjm** [rapidpro/rapidpro#1178]
**Problem Description**
Expiration options are too few. Especially with the new 24-hour window for FB and WA, we need more options to move users on to another message before the window closes.

**Feature Request**
As a RapidPro user, I want to be able to set my flows or Wait for Responses to expire at specific times so that I can send another message before the FB/WA 24-hour window closes.

**Requirements**
 It would be great to have options for 18-24 hours, and eg "Next day 8am OR 23 hours, whichever is sooner". This would allow for sending messages at appropriate times as well.

**Comment by rowanseymour** [comment]
Super simple to add more expiration values - bit of overlap with https://github.com/rapidpro/rapidpro/issues/1141 in terms of working with windows of time in which you can message a contact

**Comment by nicpottier** [comment]
Ya, I think as a first hit just adding an 18 hour expiration is an easy win here. You really don't want to get too close to 24 hours as especially if it is part of a big poll you have to account for the time to send the message out, which could be hours if you started millions of contacts at once.

So let's start with adding an 18 hour option since that comes with a lot of utility at very low cost.

**Comment by nicpottier** [comment]
(and to be clear the problem with sending millions of messages is not on the RapidPro side, but with how fast platforms even like WhatsApp can accept them. At the top rate of 45msgs/s that WhatsApp support it will take 6 hours to send 1M messages.

**Comment by rowanseymour** [comment]
We added the 18 hour option, and we can discuss the Facebook/WhatsApp trigger idea in https://github.com/rapidpro/rapidpro/issues/1141
