### ISSUE TITLE
ContactGroup matching query does not exist.

### ISSUE THREAD

**Issue by Lemmynjash** [rapidpro/rapidpro#1182]
Hello guys 

I have configured rapid pro on my local machine successfully followed all the steps from this link successfully [Rapid Pro Development Configuration Steps](https://rapidpro.github.io/rapidpro/docs/development/)

When i try to Navigate to Contacts Page i get the below error 

![The Error](https://user-images.githubusercontent.com/11975890/76837141-10130180-6843-11ea-85cc-3adb6f1b0602.png)

Kindly assist did i miss something 

Thank you 

Lemmy

**Comment by rowanseymour** [comment]
I would guess this means that the system contact groups (things like All, Blocked) didn't get created because something went wrong during org initialization. Maybe mailroom wasn't running?

These sorts of questions should be sent to the rapidpro developers mailing list at https://groups.google.com/forum/#!forum/rapidpro-dev
