### ISSUE TITLE
Implementation of Two Factor Login

### ISSUE THREAD

**Issue by hudsonbrendon** [rapidpro/rapidpro#1207]
Hello @rowanseymour , @ericnewcomer  and @norkans7  thank you very much for your feedbacks and comments in the first PR.

Continuing the feature, I would like to move up the second part of the PR. I thought we could have two new pages. the first would be displayed after login, would ask the user for the token generated in Google Authenticator, for example. And on the second, the backup token would be requested. This second would be accessed through a button on the first.

I have some doubts about where these views would be, I thought of an application called "two_factor", for example, that would store the urls, view and tests these resources. Do you have any suggestions on how we can develop this?

Greetings.

**Comment by norkans7** [comment]
I think those can be in `orgs`

**Comment by nicpottier** [comment]
Hey guys, so a few comments on the current implementation that we'd also want rolled in:

The "summary" view for these is off, that's the view you see before the section expands. These should be in a sentence like format and describe the current state. We usually want some bold in there too. Something like:

![Screen Shot 2020-04-29 at 8 03 43 AM](https://user-images.githubusercontent.com/168067/80614019-cd704780-89f2-11ea-921b-15241ead5f6c.png)

"You do not have *two factor authentication* enabled on your account."

"You have enabled *two factor authentication* on your account. You have 8 backup tokens remaining."

The codes pane needs some work so it isn't quite so ugly. Perhaps putting those in `<code>` blocks would help as a start? Showing which have been used with a cross-out might be nice too. And have them in say three columns.

![Screen Shot 2020-04-29 at 8 03 48 AM](https://user-images.githubusercontent.com/168067/80614111-ea0c7f80-89f2-11ea-8a21-89a2ad4f7a70.png)

The buttons are weird sizes.. should use the same size as the other sections.

The "Generate Backup Tokens" should probably read "Reset Backup Tokens" or the like since as I understand it this is clearing the current tokens right?

All these actions should probably require a password.

Agree with Norbert that the views should probably be in org unless you plan on moving the BackupToken model out of there.

**Comment by hudsonbrendon** [comment]
Hi Nick. Regarding the "Generate backup tokens" button, yes, it clears the current tokens.

I agree with all implementations, but I already have a login implementation developed, I will send screenshots of the screens attached, my question is: Which of the two PRs should I go up first? These mentioned adjustments (which I will still develop), or the login implementation?

Screen displayed after login requesting the token generated in Google Authenticator for example.

![token](https://user-images.githubusercontent.com/5201888/80997280-736aea00-8e17-11ea-9e53-a7b8a87dded3.png)

Screen requesting the user token backup:

![backup](https://user-images.githubusercontent.com/5201888/80997276-72d25380-8e17-11ea-944a-e458e5fbff1e.png)

**Comment by nicpottier** [comment]
I'd say those changes can all be part of the same PR.

Do we need to have a separate form for backup tokens? Or can the user just enter backup tokens in the same place they enter their normal credentials?

**Comment by hudsonbrendon** [comment]
Okay, I'll send everything in one PR. I imagine it is better to separate, it makes things more organized and didactic for the user.

**Comment by chris-erickson** [comment]
@hudsonbrendon how's this going?  We're excited to see this working..
