### ISSUE TITLE
Support for numerals other than Arabic

### ISSUE THREAD

**Issue by koallann** [rapidpro/rapidpro#1211]
We have some doubts about the numerals usage by user input according to the flow language, first if the platform supports numerals other than Arabic (0, 1, 2, ..., 9) for routers like `"has a number between"`, `"has a number below"`, etc., for example, if it could support Bengali numerals:

![image](https://user-images.githubusercontent.com/24883556/81228419-6c350f00-8fc4-11ea-862a-e60e580102ca.png)

If not, would that be desirable in the platform? Which apps would be affected in an implementation? Goflow only? This is, try to find numbers using a regex to the flow language numerals, if no matches, try by the default regex.

**Comment by nicpottier** [comment]
I think we have to try to decide where to draw the line here. I could perhaps see us adding support for Bengali for the "has a number" rules but I think we would then have to convert the number to Arabic, because the other tools at play (Elastic for one) aren't going to support us querying against those in logical ways except with Arabic numerals. (ie, `age > 35`)

Where we make that transition is the hard piece. Does it happen only when you set a contact field and results stay in their native format? If you do the conversion to Arabic numbers at the result level, then how do you get back to to Bengali if you are trying to echo out to a user? Etc..

More questions than answers here but this isn't a small thing and we have to figure out how much we want to support and how we will do so.

**Comment by rowanseymour** [comment]
I think this would have to be a feature of the `has_number` tests and what they would extract would be regular decimal, e.g. a `has_number` saves a result like...

```json
{
  "input": "hello ১৬",
  "value": "16",
  "category": "Number"
}
```

So force using `has_number` rather than doing it automatically for things like field value parsing.

I actually nearly added support for parsing out non-latinized Arabic and Hebrew numerals at one point but it wasn't clear if they were needed so it was dropped. Looked like even in those languages people were still inputing numbers from their phones using `0-9` numerals. 

@koallann have you heard something from users about needing parsing of Bengali numerals?

**Comment by koallann** [comment]
Oh, it's really complicated @nicpottier.

> If you do the conversion to Arabic numbers at the result level, then how do you get back to to Bengali if you are trying to echo out to a user?

Nic raised that important point... or maybe we can ignore that for outgoing messages? We've an U-Report customer from Bangladesh who has an "U-Report registration flow", at a certain step the flow requires the user's age and the most users pass that step by typing Arabic numerals, but many of them try with Bengali numerals.

Customer told us that while people in Bangladesh have the Arabic numerals as default, many of them prefer to use Bengali keyboard.

**Comment by rowanseymour** [comment]
Added support for Eastern Arabic and Bengali numerals in https://github.com/nyaruka/goflow/pull/970 and https://github.com/nyaruka/goflow/commit/18cfa8d97f43d2caa309d1968dd4cfaa69a3ed77
