### ISSUE TITLE
Flow Error Report handling

### ISSUE THREAD

**Issue by tybritten** [rapidpro/rapidpro#1220]
This is a split from https://github.com/rapidpro/rapidpro/issues/1217.

We're looking for an enhancement to handle errors within flow sessions which are typo's, bad flow designs, webhook errors, etc. It's hard to track down (for us, we've added slack hooks for every webhook failure) and then often requires using the session explainer if you've happened to have found the flow that failed (besides just webhooks).

Some sort of standardized way to raise errors in flow processing with good context- this expression syntax was bad. it was this flow session.

**Comment by tybritten** [comment]
@rudigiesler @chris-erickson

**Comment by rowanseymour** [comment]
There are currently two types of these "user-level" error logs..

- error events in flow sessions - things like expression errors, missing dependencies. Currently these end up contact histories 
- HTTP logs - all webhook calls, calls to NLU services.. anytime the engine makes an HTTP call on behalf of a user, we save a log in the database

Maybe we just need to have centralized place to see these. Like the new "Flow Start Log" you could also have a "Flow Error Log"

**Comment by tybritten** [comment]
We've had a lot of issues with contact histories for two reasons- one, a lot of stuff gets logged there so it makes it tough to find things sometimes. Two, they seem to be "missing" sometimes for some users. Not sure why.

**Comment by tybritten** [comment]
@putorti anything to add

**Comment by chris-erickson** [comment]
For me the problem is aggregation.  It's not clear the best way to understand that a particular webhook is failing or why.  Or that it's returning a 4XX that we need to deal with.  The ability to pipe those errors through an async handler that doesn't increase DB load would be immensely valuable.  Even if it was only a very special log message, we could use something like log stash to route specific ones to the right place.

Ideally it would be delivered to a pluggable "error handler" that implements some API for doing what it wants.  Ie. `SentryHandler`, `StatsdHandler`, `LoggingHandler`.  These handlers would be best-effort, and async with no meaningful logging, at least to the extent that they don't contribute to DB load like a webhook does.

As things are now, when a webhook is non-2XX, we grab the response body, and send a message into slack as is relevant.  Kinda bad when you slam something with a malformed body mid-spike, or in our case, exceed S3 limits on an external service and see a never ending flood of Slack messages (when you're not being rate limited by slack...).  Worse, this adds DB load as we write out the results of _that_ webhook or flow run (which also might be 4XX!).

**Comment by nicpottier** [comment]
So what you are talking about here is super special to your use case, where you as a hoster also are managing the webhooks. That isn't at all a typical thing, so isn't something that we are likely to spend a lot of time optimizing for.

I guess my first question is why are you depending on RapidPro to handle all this logging? Your services presumably have logging themselves and have a full context as to why they failed (much more so than RapidPro does) so shouldn't they be doing the logging?

**Comment by chris-erickson** [comment]
Not every service we call is one we manage, and wouldn't any user enjoy the ability to pipe captured errors to some centralized place?  Absent this, you don't really know at all that things are failing unless you're watching user logs.  I wonder if this is _more often_ the case for someone who is largely relying on their party services, would people even know?

One example, we call SmartyStreets' API to clean up addresses.  If that were failing, we would never proactively know.  We have all kinds of these things so we know certain things are behaving badly, or a user ended up at some point with data in an incorrect state:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3322287/81851498-2d9cd880-951f-11ea-875b-99bb0dd00c52.png">

Right now in slack we get _"this webhook is not a 200, here's some data and a contact link, good luck"_.  (Some do a bit more handling, like check if the error message contains X, tell the user Y, but that's not easy)  If these could funnel to something like Sentry, we could much more deliberately aggregate and act on them.  I'll again note that this causes additional DB load, and more often than not we're already under load when a service is falling apart and this compounds it.

Thanks for the discussion, hopefully we can zero in on something that's a good value for everyone.

**Comment by nicpottier** [comment]
Sure, ya I just don't think Sentry is likely the solution that most of our users would use, though I certainly appreciate the appeal to that.

As Rowan mentioned above, perhaps having a place where you can see "recent flow errors" or the like that lists errors across your organization (regardless of type) and lets you go visit that contact would be an obvious first start there.

From an HTTP level this is all already saved and available so having an "integration errors" page or the like wouldn't be a huge lift.

**Comment by chris-erickson** [comment]
I wouldn't look a gift horse in the mouth, to be sure.

On a slow day we see perhaps a couple dozen web hooks errors that we know about.  Some are transient outages, some are a user reaching a point in a flow they shouldn't have (webhook fails validation and we note that in slack, usually indicates a bug in an earlier flow), some are a new deploy of a service breaking an assumption, etc.

Whether it's sentry or logstash->ES I'd prefer to be more proactively notified of things, or be able to silence others.  I'm not sure a list of recent errors gets us much further than dumping a 500 into slack.  Especially since some "500's" are actually consistency issue we need to explore.  Like, webhook X returned data that was missing something we expected to be there and needs to be investigated.  So, that's going to appear in a flow log only if we don't assert that and send it to slack manually.

@rudigiesler how are you using slack for these things?

**Comment by rudigiesler** [comment]
So for us, I think sentry would be the gold standard. We could group errors together, assign issues to people, comment so that we have a history of context about the problem, set up notifications, all the good things that Sentry gives us.

Having a place to view all the errors together will be a great improvement though. There are two things that it doesn't solve for us:
1. Noisy non-important errors hide more important errors. This is also an issue with our slack implementation
2. There's no alerting on errors, we don't want to have to remember to check for errors every day. Since we have control over the database, we could alert on new rows being added, which could solve that issue for us.

The way we're currently using slack webhooks is, for every failed webhook call, we create a message in a slack channel with as much context as we have in that point in the flow. This means that we have visibility on webhook failures, but not on flow errors.

**Comment by nicpottier** [comment]
Yep, to be clear, totally understand the desire here for the larger orgs. And I would say the class of errors you would want reported would be:
 * errors when evaluating expressions
 * errors when calling a webhook / classifier / airtime transfer
 * errors when sending or receiving messages on a channel on an org (bad API token, throttling, whatever)

I could even envision an "error" action that lets flow authors generate errors manually, say when you end up on a branch that you don't expect to ever reach. (an "Other" branch for example that you believe to be impossible or very infrequent)

So I think all of these things could be classified as "Org Errors" or "Workspace Errors". We shouldn't be thinking of these just as "Flow Errors".

So from that then the question is what do we do with them. Connecting to Sentry I agree would be great for those organizations that are more sophisticated. So I could imagine at an Org level you can connect a Sentry endpoint (would be a "Project" on their side) and all errors automatically get shipped their way and you get all the usual tools to mute, etc..

But understand that is a tiny fraction of RapidPro users that have that kind of sophistication, so we would also want to expose these errors somewhere in the organization as well. Maybe there's an `OrgError` model that has super simplified `type`, `title`, `metadata`, `created_on` columns and those can be viewed somewhere? And those get culled after 7 days automatically? If you hook in an Error (Sentry) service then those additionally get sent over to that service? And someday someone can plug in something apart from Sentry?

That's the kind of approach I think we would support. Just plugging in Sentry errors at an installation level isn't. Nor doing all the work around collecting these errors without having a benefit to the majority of users.

**Comment by chris-erickson** [comment]
I'd probably be reluctant with an option that by default writes to the DB.  Anything that adds more load when we're likely already loaded is concerning.  We're regularly trying to find strategies to keep IOPS from peaking too high.

But if the error thing by default was a noop, and a general log-to-the-db handler was a reference implementation, we would be happy to implement one that has it's own internal implementation for something like logging to disk or http.  That make sense?  I think we mostly agree on the premise here, but I'm not necessarily saying the only way this can be done is `<insert error tracking system here>`.

And yup, I think "workspace errors" is accurate, it would be super cool as something akin to an `assert` in flows when some flow logic bug caused a user to end up in a bad state someone needs to intervene with.  We'd go nuts with this stuff.
