### ISSUE TITLE
Show where people expire in flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1228]
People really like using flows and our activity counts for analytics in flows, but we don't currently make it easy to visualize where someone has expired from a flow. We show where people currently are waiting which is part of the solution, but having a way to show where attrition happened would be super useful for people trying to optimize their flows.

**Comment by rowanseymour** [comment]
I like this, even yesterday I had to explain to a user that their contacts disappeared from a flow because them expired at particular node that she'd seen them waiting at.

Confusion occurs when 1 != 2 + 3...

<img width="262" alt="Captura de Pantalla 2020-05-28 a la(s) 16 05 09" src="https://user-images.githubusercontent.com/675558/83193773-3683d180-a0fd-11ea-96b9-4189f72b52b1.png">
