### ISSUE TITLE
Tools to delete/purge contacts

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1241]
It would be nice to have some easier tools to allow users to delete a batch of contacts from the system.

As a start, perhaps allowing someone to delete all the contacts in a group.

We could then add other things that would maybe let you build groups based on inactivity or the like to help people clear out dormant contacts they no longer want.

**Comment by rowanseymour** [comment]
I think deleting contacts in a group sounds reasonable tho maybe we can brainstorm more about where we want to go with this.

My first thought was "everything is a flow!" but I don't like the idea of a flow directly deleting a contact.. I prefer the "Recycle Bin" model of being able to "archive" or "deactivate" things via different mechanisms, and then from that view, with a giant flashing red modal warning, actually delete contacts. The Recycle Bin in this case might be a user group or a system group.

Having an easy way to get a "last seen" date for contacts seems to be central to all of this - i.e. the last time we got an incoming message from that contact.

Unfortunately you can't create a dynamic group with a date query that is relative to "now".. since now is always changing. Darn it progress of time!

There would however be nothing to stop users from searching from time to time with a query like `last_seen < DATE`.. delete all the contacts that are returned.. or save as group and then delete the group?

Users could run campaigns to send all their contacts thru a flow every night and check  `@contact.last_seen_on` to determine if that contact is what they consider "inactive". Downside of that is they'd be sending lots of contacts thru a flow on a regular basis which only affects a few contacts.

Or we could just decide what "inactive" means.. we put contacts into a `status=archived` state after X number of days. You can imagine having a system group like All and Blocked called Archived and from there you can delete contacts.

**Comment by nicpottier** [comment]
I kinda like the recycle bin idea though having yet another status for contacts sounds a bit confusing. Also if we are saying we are charging per contact, then paying for "archived" contacts feels like maybe it would be confusing too. (though I suppose same could be said for blocked/stopped contacts)

I think if we at some point start considering charging for "active contacts" then after some discussion we decided that would have to be based on last msg style interaction. IE, not something as simple as running them in a flow. But it does also pose the question whether it should only be those who send an INCOMING messages within a period.

For either of those one concern is that updating an entire contact field row and associated elastic row for every contact that enters a flow that sends a message is actually quite expensive. Wonder if we need to model that differently, perhaps in another table entirely. (though that gets trickier from a search perspective)

**Comment by rowanseymour** [comment]
I think paying for archived contacts is fair in the sense that you're still paying storage of your archived/blocked/stopped contacts. And if it's really easy to delete contacts in that state (e.g. a system folder with a _delete all_ button) I don't think users could complain.

Even if we didn't add that status, if we say that you can delete from a group, then I imagine some users will use a custom group like a Recycle Bin.

**Comment by ericnewcomer** [comment]
I think a more positive spin on this is that they aren't so much as archived as they are "slipping away" in intercom parlance. As, hey, you should engage with these important users of yours. If they want to give up on them and delete them to save some coin, well, then that's a decision they can make. But seems rightful to pay for opportunity to re-engage them in an automated way. But ya, how billing works is not really a rapidpro concern, but I think the same argument exists. These contacts are ones you are losing that you may want to take action with.

It does seem we need some way to model last_active efficiently whether we use MAU or not. I think that probably needs to be last inbound or outbound message for that contact. If it's only inbound then, MAU is effectively incentivizing people to send spam since they only pay for their pitiful response rate which doesn't seem right. That said, last_seen (last inbound) is probably a super useful datapoint for monitoring engagement or modeling campaigns.

**Comment by rowanseymour** [comment]
Closing as we now have.. 

 * contact.last_seen_on - accessible in expressions and searching
 * archived as a contact status - you can archive contacts from flows
 * from Archived folder of contacts, you can bulk delete
