### ISSUE TITLE
Flow Editor calling "next" as http instead of https for paginated responses

### ISSUE THREAD

**Issue by koallann** [rapidpro/rapidpro#1242]
We are facing troubles when the Flow Editor receives paginated responses from API with the `next` field filled because it comes as `http` instead of `https`, so the browser is blocking the subsequent request, for example, when we try to use the `Enter another flow`:

```
xhr.js:172 Mixed Content: The page at 'https://host/flow/editor_next/uuid/' was loaded over HTTPS, 

but requested an insecure XMLHttpRequest endpoint 'http://host/api/v2/flows.json?archived=false&cursor=cD0yMDE5LTEyLTE5KzE4JTNBMjUlM0ExOS44NDM5ODAlMkIwMCUzQTAw'.

This request has been blocked; the content must be served over HTTPS.
```

Are we missing some setting?

**Comment by matmsa27** [comment]
Hi everyone, can one help us with this?

**Comment by rowanseymour** [comment]
From a quick look at the DRF code it seems they rely on `request.build_absolute_uri()` to build those URLs.. does that always return a HTTP URL on your deployment?

**Comment by markirius** [comment]
well, I suspect that the http server is not properly redirecting requests, when you access the request with json data through the browser developer tools, if the requests are directed to a valid https and only the browser is directing to http, and assuming that there is nothing wrong with the code, I think that the application itself is not the problem, so assuming the http server is the case, leave it set on your http server so that the directions are http in the "api url's only", be directed to https, do this only for the urls of the api, done this and test the situation and see how the application behaves.

**Comment by rowanseymour** [comment]
Closing this as it does seem to be a server configuration issue.. you can reopen if you discover something that suggests otherwise.

**Comment by matmsa27** [comment]
Thanks @rowanseymour :)
