### ISSUE TITLE
Ticket Service: RocketChat

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1251]
hey team, we've started building a RocketChat app for RapidPro to make it available to use as a Ticket Service in RapidPro: https://github.com/Ilhasoft/Rocket.Chat.App-RapidPro

We're following the same approach as the [zendesk app](https://github.com/nyaruka/zendesk-app) that Nyaruka has built, enabling for changing branding. In some weeks, we're sending the PR with the support for that on RapidPro and mailroom. My team may have some questions about it, so let's use this issue to discuss.

**Comment by nicpottier** [comment]
To add to Rowan's thumbs up, this all sounds good to us. What would this kind of integration look like for the end user? I see you pointed to a JS app, can end users install that as an app in RocketChat?

**Comment by koallann** [comment]
Yes, @nicpottier. RocketChat has a marketplace like Zendesk and each app can provide its own settings for end users, look at an example:

![image](https://user-images.githubusercontent.com/24883556/86486366-7a3bad80-bd31-11ea-9049-e3dc9c7f6aad.png)

## Integration

In our case we will initially need to provide settings fields for `auth_token` and  `user_id` (from an admin/manager user) because those are requirements to call the RocketChat Rest API. It's important to highlight that RocketChat is a platform for team communication which has a omnichannel module, so full support to omnichannel through RocketChat Apps framework is not yet present, forcing us to use the rest API.

Also, note that RocketChat apps are developed using the [Rocket.Chat.Apps.Engine](https://github.com/RocketChat/Rocket.Chat.Apps-engine), a framework for building general-purpose apps for the RocketChat platform, so we can register HTTP endpoints, chat commands, some event callbacks, etc.

Steps for integration would be:

1. In RocketChat, an admin user installs the RapidPro app and generates an `auth_token`/`user_id` pair to set in app settings. As said that auth pair is needed to call the RocketChat Rest API;
2. In RapidPro, the RocketChat ticket service integration requires the RocketChat host URL and a token is generated to be set in app settings field;
3. In RocketChat app, the rest API will be like:

    - `/room.create`: To open a new ticket;
    - `/room.close`: To close a ticket;
    - `/message`: To forward messages from RP.

    Therefore, Mailroom would interact with these endpoints as needed.

- A first question: can we set attachments to a message from RocketChat human agent?

- Another question: should we send the bot's previous messages to the human agent to contextualize it?

## RocketChat room events

In the context of rooms creation on RocketChat, the following events can be emitted:

First, RocketChat allows us to enable/disable rooms creation when no have an agent available.

- `Taken`: When an agent takes a ticket;
- `Queued`: Depending on previous setting, this event is emitted if no have an agent available, the user goes to a waiting queue;
- `Forwarded`: When an agent forwards a ticket previously taken to another agent;

We treat these room events through an app between RP and RocketChat that [starts specific flows](https://rapidpro.io/api/v2/flow_starts) to each event type:

1. To `taken flow` we need two things first:

    - A group for users in human attendance, let's call it as "human attendance";
    - A trigger of type "uncaught message" for contacts in "human attendance" group that starts a flow to send messages to RocketChat.

    So this flow add the contact to "human attendance" group.

2. To `queued flow` we only have it to notify users that they are in a waiting queue.

3. To `forwarded flow` we only have it to notify users that will be forwarded to another attendant section.

The main goal with these events is to avoid losing user attendance as much as possible, proved to be very effective for us in this pandemic context and precautions against COVID-19.

So, one more question: does it make sense to fit these events into the RP ticket model or should we keep the flows/groups/triggers approach?

**Comment by rowanseymour** [comment]
I would suggest that you take a look at the existing Email and Zendesk integrations we've added to support the new Ticket services feature. If we add RocketChat as a ticketing service then it needs to fit within those same workflows. 

 > can we set attachments to a message from RocketChat human agent?

Yes there's no reason this couldn't be done. We'll likely add support for that in the Zendesk integration at some point. It's just not something that was considered important for a first release.

> should we send the bot's previous messages to the human agent to contextualize it?

The way the email/zendesk implementations work is that there's an Open Ticket action and the flow creator controls what is sent to the ticketing service (via expressions) to open a ticket and provide context. If we decide later that tickets need more context, we could maybe add something in expressions so that all ticket services can benefit.

The current ticket implementation is pretty basic - it essentially just sets up forwarding of messages between the contact and a ticket in an external system. We wanted to get that out there so people could start playing with it and tell us what works and what doesn't. We have some ideas of what we'd like to add next but now is your chance provide some suggestions. What we think the next steps should be are...

1. Pausing of contacts - when a ticket is opened, put the contact into a paused state so that they don't get started in flows and campaigns etc

2. Triggers for when tickets are opened and closed - instead of us automatically pausing a contact - let users control that themselves via a flow.. and do whatever else they want to do. 

Maybe 2. is a place we could let users handle the different RocketChat events, e.g. the flow is started with some params that include information about the state of the room in RocketChat ?

**Comment by koallann** [comment]
Exactly, @rowanseymour.

We also added some fields on the contact to control the creation of rooms on the RocketChat side; for example, in the pandemic context, we have a priority field - defined from the user's symptom inputs - that's passed to RocketChat in order to sort tickets by urgency...

So, at this point, it's ideal to develop an UI (flow editor) to control these variables or keep the current approach of contact fields with some tweaks?

**Comment by rowanseymour** [comment]
Hmm I notice in Zendesk they have a priority field on each ticket which can be `Low | Normal | High | Urgent`. What is the equivalent in RocketChat?

We could model this is an advanced property of the open ticket action, if we can define something that makes sense across different ticketing services.

**Comment by koallann** [comment]
It's customizable in RocketChat, as well as for the other `"department"` field.

**Comment by rowanseymour** [comment]
I think for now we should be aiming for a simplest implementation - we can add more advanced features later once we get the basics working, i.e. the back and forth of messages, closing of and reopening of tickets.

Then later we can look at what additional features make sense across different ticket service implementations. My initial inclination is that a priority field is sufficiently generic.. a department field less so.

**Comment by koallann** [comment]
I agree... So, as we are migrating our RocketChat integration to the tickets model we have some legacy fields to fit in this new integration, but now I guess a possibility would be to handle these fields in the ticket service implementation, reading them from the "open ticket" action body, something like:

![image](https://user-images.githubusercontent.com/24883556/87453308-b0eab100-c5d8-11ea-985e-f8570152540f.png)

What do you think?

**Comment by rowanseymour** [comment]
If that works for you guys to maintain your existing behaviour with RocketChat then you could do that.

For the code that we merge into mailroom, I suggest that we worry about additional fields like priority later.
