### ISSUE TITLE
Folders vs. Nested Labels

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1295]
Messages have labels which can be nested in folders.

Flows have labels which can be nested under other labels.

This not being consistent can lead to confusion and/or inconsistent UI treatments. Flow labels have their own membership and while message label folders are rollups of their contained labels.  We might consider moving flow labels to match the behavior of message labels.

**Comment by rowanseymour** [comment]
.. or ditch rolling up of labels on messages? I imagine now that we purge messages after 90 days it's not such a big problem but that makes for some hard to optimize queries.

**Comment by nicpottier** [comment]
How does CasePro use labels these days? Is that still a big piece of it? I definitely don't love the way we roll up counts on labels, it is just a bit nutty and I suspect this is a feature that is so seldomly used that it is more confusing than helpful to have.

**Comment by rowanseymour** [comment]
Unfortunately yes it's still a fundamental part of CasePro because labels determine access to messages - partners get granted access to a set of labels, and their inbox becomes all the messages with those labels.. I would love to travel back in time and plead with us to not go that route. Am trying to remember why we decided to support this for messages in RP.. and I could be wrong.. but I have vague recollections of us justifying on the basis that.. "we need to display something on the page when you click the parent label"

**Comment by ericnewcomer** [comment]
Don't feel we need rolled up counts, the scenario I want to avoid is things attached to a label that also has child labels. That is super weird to me.

**Comment by rowanseymour** [comment]
Both of these are on their way out in the new UI and we've already disabled creating new labels with parents
