### ISSUE TITLE
How to host Rapidpro on hostgator server?

### ISSUE THREAD

**Issue by ram009** [rapidpro/rapidpro#130]
Could some one point me to a step by step guide on how to host the Rapidpro on Hostgator server.

**Comment by nicpottier** [comment]
There isn't any such guide as far as I know of. I don't think you are likely to be able to get it running on Hostgator though maybe they are more capable than I think.

You'll need some dedicated machines (virtual or otherwise) will full root to install all the dependencies and get everything configured.
