### ISSUE TITLE
Missing implementation of start filter at RunsEndpoint

### ISSUE THREAD

**Issue by johniak** [rapidpro/rapidpro#1300]
For the _RunsEndpoint_ at ` GET /api/v2/runs.json` start filter is documented (you can see it also in API docs).
https://github.com/rapidpro/rapidpro/blob/master/temba/api/v2/views.py#L3022

As documentation says this filter should filter FlowRuns by FlowStarts uuid, but there is no implementation for this at _RunsEndpoint_

So I added it in this pull request https://github.com/rapidpro/rapidpro/pull/1299

**Comment by rowanseymour** [comment]
I don't think we've documented anywhere that runs are filterable by start - start is mentioned in that list because it's a field on the returned JSON. It's also not quite as simple as adding a clause to filter runs because there's no index that would return runs ordered by modified_on for a given start, and we try to ensure all API calls hit perfect indexes (not uncommon to have millions of runs per start).

**Comment by johniak** [comment]
right, I wrongly understood documentation 
`https://rapidpro.io/api/v2/runs` on details filters are just not shown
the query parameters are only shown on main api docs page
about indexes:
I don't see any additionional indexes on _FlowRun_
https://github.com/rapidpro/rapidpro/blob/master/temba/flows/models.py#L1791

I see that this type of indexes on _FlowStart_ but not on _FlowRun_.

**Comment by rowanseymour** [comment]
Not all of our indexes are managed by Django - see https://github.com/rapidpro/rapidpro/blob/b4d057837395c58c42a3458ec7eb2b153b3cbad4/temba/sql/current_indexes.sql#L52-L72

**Comment by johniak** [comment]
oh nice!

**Comment by rowanseymour** [comment]
We're always open to adding new features to the API but every new way of filtering is then something we have to support for the foreseeable future and every new index is an overhead - so unless someone has a essential usecase for needing this I'm going to close this issue for now.
