### ISSUE TITLE
Attachments for ticket messages

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1309]
In both directions where supported by the ticket service

 - [x] Zendesk incoming
 - [x] Zendesk outgoing
 - [x] Mailgun incoming
 - [x] Mailgun outgoing

**Comment by matmsa27** [comment]
Hello @rowanseymour , several users currently use the email ticket service, but the lack of support for media has limited more the exploration of the ticket service in RP. Do you already have something defined about how this implementation will be done for media support in the ticket service? 

We want and are available to contribute a lot with this feature, mainly so that our [PR](https://github.com/nyaruka/rapidpro/pull/2909) on the new service ticketer also supports this.

**Comment by rowanseymour** [comment]
Hi @matmsa27 we recently added support for attachments in both directions in the Zendesk integration and hopefully that would be a good pattern for how to do it with RocketChat.

Are you referring to the Mailgun/Email integration? It doesn't yet support attachments.

**Comment by matmsa27** [comment]
What do you recommend to our PR on RocketChat ticketer? We can add this feature on this PR opened, or after that PR merged?

About the Mailgun/Email integration, yes I'm referring to this.

**Comment by rowanseymour** [comment]
Sorry about the delay - part of the reason I wanted to add attachment support to Zendesk before we merge the RocketChat stuff was to figure out a good pattern for all ticketer services to implement attachment support which I think we have now. So please go ahead and add support for attachments to the RocketChat implementation and then we can try to get that merged sooner than later.

It shouldn't be too much work to finish adding support to Mailgun/email.. I hope I can get to that in the next few weeks

**Comment by matmsa27** [comment]
No problem @rowanseymour . Thank you, we will implement the attachment support on RocketChat ticketer on the next days and update the PR. Thank you.

**Comment by koallann** [comment]
Hi @rowanseymour, in our case we need to pass a custom request to download the media from RocketChat, is the implementation of a [BuildDownloadMediaRequest](https://github.com/nyaruka/courier/blob/master/handler.go#L38) expected?

**Comment by rowanseymour** [comment]
I don't think that would work.. can you do something like how Zendesk fetches attachments?

**Comment by koallann** [comment]
Unfortunately, RocketChat requires a access token to get the media, to be more precise, requires the headers "X-Auth-Token" and "X-User-Id", created from an admin user in our case.

**Comment by rowanseymour** [comment]
Still not quite following.. this would be mailroom making a request for media from RocketChat.. so can't it just make a request? The `BuildDownloadMediaRequest` struct in courier is because the handlers are unified and they tell courier how to request the media on their behalf.. we don't really have such an architecture in mailroom for ticket services.

**Comment by koallann** [comment]
The [SendReply](https://github.com/nyaruka/mailroom/blob/c80d240da950c2fa638f729ec5a94ae17eb7d19a/services/tickets/utils.go#L79) receives the `fileURLs []string` that is iterated by calling the [fetchFile](https://github.com/nyaruka/mailroom/blob/c80d240da950c2fa638f729ec5a94ae17eb7d19a/services/tickets/utils.go#L127) function, which in turn makes a GET request to the given url. That GET request will fail (403 Forbidden) to a RocketChat media url because the headers `"X-Auth-Token"` and `"X-User-Id"` are required by RocketChat.

**Comment by rowanseymour** [comment]
Ah ok that makes sense now 😄  

Yes - maybe we just add something like `BuildAttachmentRequest(url string)` to `models.TicketService`, and then pass the service into `ticket.SendReply`

**Comment by rowanseymour** [comment]
Closed by https://github.com/nyaruka/mailroom/pull/375
