### ISSUE TITLE
Allow sorting of contacts by Created On or other display fields

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#133]
It would be mighty useful to be able to be able to sort the contact list by the display fields for an organization instead of just defaulting to sorting by name. Perhaps having the column headers be clickable to set and toggle ordering.

**Comment by jlev** [comment]
Would also be really helpful to be able to search and make dynamic groups with the contact.created_on field

**Comment by rowanseymour** [comment]
Hi @jlev. Dynamic group re-evaluation is a current pain-point at scale, so we recently made some changes so that they can only be based custom fields and urns, and long term we want to integrate elasticsearch to handle the UI search views and dynamic groups. We could tho make `@contact.created_on` accessible in expressions and then users would be able to copy that into a custom field.

**Comment by rowanseymour** [comment]
We added sorting by custom fields, and I've opened new issues for created_on in expressions and dynamic groups: https://github.com/rapidpro/rapidpro/issues/767, https://github.com/rapidpro/rapidpro/issues/768
