### ISSUE TITLE
Editors should be able to see channel logs

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1338]
We generally say editors are the same as administrators except they can't add / remove users, but that isn't true when it comes to channel logs.

I think I'm of the opinion that we really should treat them the same. An editor can totally wreck your account from a functionality perspective by mucking up flows etc.. so it isn't really a matter of "locking down" your account in any way.

Suppose the argument might be that they could see credentials on an account that they may not normally have access to. IE, Twilio tokens.. to which I would say maybe we should just mask those for editor accounts instead. Channel logs are kind of a necessity to understand why messages aren't failing so we have to have it a bit more open.

So I'd vote to turn on channel logs for all editors but try to skim out credentials from the logs.

**Comment by rowanseymour** [comment]
To be honest I've never really thought much about editors.. but do want to stop and think if `same as administrators except they can't add / remove users` what most workspace admins are looking for when they add people as editors rather than fellow admins.

I can imagine being an admin and wanting a class of user who can edit contacts and flows, but can't for example do stuff like delete a channel, or my zendesk integration.

**Comment by rowanseymour** [comment]
Btw I haven't yet merged https://github.com/nyaruka/rapidpro/pull/2968 because I'm still waiting to hear some thoughts on what we think Editors should be. I think I would still lean toward "they can edit/manage flows and contacts but not administrate workspaces" as being potentially more useful to users.

**Comment by nicpottier** [comment]
I personally think the way we describe it is right. Editors don't get to grant new permissions to others, but you can do everything else.

I guess it could be worth talking about what an "owner" role means here too. We have talked about that being tied to billing primarily, but another way to look at it could be that only account owners can add new users. Admins can do anything except add users and editors can only edit flows / contacts / triggers etc..

That's a bit of a bigger change though.

For #2968 are there any API endpoints that editors can't access? You can't delete channels etc through the API anyways can you?

**Comment by rowanseymour** [comment]
Shame we can't hear from some users about this because my gut feeling would be most admins think the _Editor_ role is more restricted than it is. For example I really don't think anyone expects that editors can do admin'y things like delete channels, change your workspace's 2FA settings etc.

I initially approved #2968 because if the goal is just to make Editors the same as admins without user management then.. giving them API access is consistent with that.. but on reflection I'm not so sure that's what users expect/want. If I was an admin I think I'd want a class of user more in the middle between administrator and viewer.

The API doesn't let you delete channels, but you can delete contacts, groups, campaign events, resthooks.. so I guess my bias would be saying editors can't do that.. and I've also not heard users asking for Editors to have that access.

Not sure what to do about Owner.. I guess only they can delete an org. Am concerned that if we make any more permissions restricted to Owner then inevitably we'll get complaints from people whose workspace owners are no longer around.

**Comment by rowanseymour** [comment]
Just as a data point this is how Zendesk describes their different roles and account owners - tho they don't have a read-only class of user like Viewer https://support.zendesk.com/hc/en-us/articles/203661776-Understanding-Zendesk-Support-user-roles#ariaid-title3

**Comment by nicpottier** [comment]
I mean, #2968 is from a user complaint, so we do have data here. We also have consistently described editors as admins without the grant role.

Giving a new person access to your account is a different class of thing. Plenty an editor can do to muck up your account by changing flows so adding extra restrictions doesn't really prevent anything. You are trusting editors to not blow shit up.

**Comment by ericnewcomer** [comment]
Ya, to me this feels somewhat like semantics. "Editor" does on one hand feel like somebody who can only edit something, ie, not add or remove things. But we've always said an editor is just somebody who can make mutable changes -- and that isn't restricted to just editing flows. I don't see any benefit to having a role that edits flows but can't update other things. As @nicpottier said, they can already do the most destructive thing in the system. So far, I don't think where we have drawn the line has caused issues for our users, so I don't see any strong argument to changing that.

**Comment by rowanseymour** [comment]
Ok I've personally never described an editor as anything to anyone and always assumed that they don't have the ability to administer things channels, 2FA, org settings. 

And messing with flows and contacts is not that destructive - there is an audit trail and revision history.

Not convinced but apparently outvoted!

**Comment by rowanseymour** [comment]
Ok sorry to labour a point that I'm in the minority on but this really feels like a mistake. Ok you guys have told customers that Editors are Administrators without user creating, but it turns out that that isn't true and there's lots of little ways in which that hasn't been true. For example as I've just noticed helping a user, only Administrators can create new child workspaces - that feels correct.

So we have an opportunity to rethink what an Editor is or cement the idea that they are the same as Administrators minus user creation. Most users will never ask us what an editor is, so a more important question might be what do they assume from our UI when they create editors rather than administrators:

<img width="301" alt="Captura de Pantalla 2020-09-14 a la(s) 12 21 28" src="https://user-images.githubusercontent.com/675558/93117811-fda84200-f684-11ea-8135-1314247ae6ef.png">

I don't get dismissing this is as semantics. UIs are semantics. Users aren't creating editors thinking that that person can delete their Zendesk integration.

I would say at the very least, Editors don't get to do..

 * User management
 * Child workspace management
 * 2FA settings

**Comment by nicpottier** [comment]
Sure, I'm fine with that.
