### ISSUE TITLE
USSD External Channel - Latest courier (highly required) but incompatible with current RapidPro version.

### ISSUE THREAD

**Issue by ekeeya** [rapidpro/rapidpro#1358]
We are implementing a USSD channel for a UNICEF task. One of the requirements is to indicate to the end user when a conversation has ended. In order to achieve this, changes have been made to courier at https://github.com/dsmagicug/courier which where later merged here https://github.com/nyaruka/courier/pull/333. following the discussion at 
https://github.com/rapidpro/rapidpro/issues/1298 with @kitandara and @asseym 

We opened up an issue yesterday about RapidPro missing the `status` field in the contacts model and courier making wrong SQL queries at. 
https://github.com/rapidpro/rapidpro/issues/1356  but perhaps I did not introduce my self as part of the above USSD channel implementation team.

The issue of `status` field is fixed at  https://github.com/nyaruka/rapidpro which we are going to use as opposed to the earlier stated https://github.com/rapidpro/rapidpro in the issue above

However the insert SQL for contacts in courier nyaruka branch needs to change as well. See diff below. 

https://github.com/nyaruka/courier/compare/master...ekeeya:master 

Thank you

**Comment by rowanseymour** [comment]
Nothing in courier needs to be changed. People running RapidPro have two options - run the stable release versions of RapidPro, Courier etc listed in the README, or run the latest version of everything. The latest version of everything is what we run but obviously don't recommend that other deployments do that because we can't make any promises about things working. For your development work though, you should run the latest version of everything. At the end of the month we'll make a new stable release (6.0) and update the stable versions in the README.
