### ISSUE TITLE
Getting started dialog

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#139]
I wonder if having a 'getting started' dialog could help for new RapidPro users, such as to add a relayer, or contacts, or build a first flow.

**Comment by ericnewcomer** [comment]
After logging in, there's an overview section of every major part in the system. Building flows, there's a library of videos and we attempt to onboard users in the flow editor as gingerly as possible. Granted there's lots of power buried, but this is by design to not overwhelm new users. Is there a particular part of the new user experience you think should be improved?

**Comment by citizenrich** [comment]
Doh. Ahh, I had forgotten as had not seen welcome stuff recently. Closed...
