### ISSUE TITLE
Firebase Configuration Not Working

### ISSUE THREAD

**Issue by Hareet** [rapidpro/rapidpro#1395]
Referenced comments:
https://github.com/rapidpro/android-channel/issues/20#issuecomment-497759968

We created a custom Android Channel apk which has credentials to our Firebase setup.

I've added the respective Server Key to `temba/settings.py` as `FCM_API_KEY`, but when I send a message, nothing happens until the phone auto-syncs on its polling duration. 

I am able to run a shell of PyFCM, and successfully execute:
```
result = push_service.notify_single_device(registration_id=registration_id, data_message=dict(msg="sync"))
```

This forces the android client to sync. I retrieved the `fcm_id` of the client from RapidPro Django's logs. This should verify that the client is registering with Firebase correctly, sending a valid `fcm_id`. The credentials `FCM_API_KEY` work successfully to talk back to the client. I'm just unable to get RapidPro to trigger fcm to push to the client.

My expectation is that after the above configuration, I can go to contacts and send a message which should get recognized immediately by the android client. Instead, the current result is waiting for the android client to poll the server, which triggers a sync. The Android App was left running in the foreground of the client, and eventually falls asleep.

I've tried adding a print statement in [trigger_send](https://github.com/rapidpro/rapidpro/blob/master/temba/orgs/models.py#L688) to see what was inside `msgs` but looks like it didnt run that piece of code. Trigger_send invokes [trigger_sync](https://github.com/rapidpro/rapidpro/blob/643db6aa881db21f2739473109304d3494eb5efe/temba/channels/models.py#L980) which contains the pyfcm line i manually tried above.

Any help on trying to verify that RapidPro is talking to Firebase correctly and will push calls to the Client immediately would be appreciated. Thank you!

**Comment by kennsippell** [comment]
Repro steps:

1. Install latest Android Channel on android device
2. Configure new RapidPro workspace and add Android Channel
3. Create an contact with `+tel` through RapidPro interface
4. Send message to contact through RapidPro interface

Expected
===
Firebase should cause Android Channel to send SMS shortly after clicking "send" in RP interface

We are expecting that because of [this documentation](http://litlfred.github.io/rapidpro/docs/components/)

> RapidPro in turn communicates new outgoing messages to the Android device by notifying it to sync with it using Google Cloud Message (GCM). This lets the server ‘push’ a ping to the client to call home.

Observed
===
Messages are sent through Android Channel only at regular scheduled polling intervals. Based on Android logs on the channel, firebase message is never received.

Is this set of steps expecting the correct behaviour from the Android channel/Firebase? Can somebody confirm that we understand the intent of the messaging here? If confirmed, I'm happy to try to investigate and fix, but currently not 100% sure I've wrapped my head around this.

**Comment by nicpottier** [comment]
Are you running mailroom? It is actually mailroom that should be notifying the relayer of new messages, at least ones that are triggered via flows. Do you see the same behavior for flows AND broadcasts?

**Comment by kennsippell** [comment]
I'm not sure what mailroom is. We reproduced this via textit.in - is that running mailroom?

**Comment by nicpottier** [comment]
You should open a ticket on TextIt if you are running into problems there. Look for the dialog box in the lower right.

**Comment by kennsippell** [comment]
Okay, I can do that.  We are self-hosting RapidPro and our primary objective is to get that self-hosted version sending messages quickly - so we want this Firebase integration working. My intention is just to say that this appears to be broken on our self-host instance but also broken on TextIt - so that increased our confidence this is a system problem and not a self-host problem.

**Comment by nicpottier** [comment]
Well, if you don't know what mailroom is then you probably have some more setup to do. That's one of the core components.

Lots of things can get around syncing of the Android relayer, we generally only recommend it for pilots.

**Comment by kennsippell** [comment]
From the docs: 

> You will need a running Mailroom instance in order for any flows to be executed.

Our flows are working fine - just slow, so yes, we are running Mailroom

**Comment by Hareet** [comment]
Yes, we have mailroom configured 👍 
@kennsippell

**Comment by Hareet** [comment]
@nicpottier Here is our stack:
- RapidPro (Django) v5.6.5
- RapidPro (Celery & CeleryBeat) v5.6.5
- Courier v5.7.0
- Mailroom v5.6.2
- RapidPro indexer v5.6.0
- RapidPro Archiver v5.6.0
- RapidPro Android Channel

And all of the associated databases are configured and running (postgres, elasticsearch, redis)

>Lots of things can get around syncing of the Android relayer, we generally only recommend it for pilots.

Is there a list or documentation you can point us to? We are running a large pilot program.

**Comment by nicpottier** [comment]
I just tried this on TextIt and it seems to do the right thing for flow interactions. Direct message broadcasts (IE, just from the inbox or the contact page) do not trigger syncs though, opened an issue for that here: https://github.com/nyaruka/mailroom/issues/392.

Note that unless you are building your own app with your own FCM key, this won't work. Since the FCM key is tied to a particular app, you need to build / distribute the app yourself with your own FCM key and configure the mailroom side appropriately. (`MAILROOM_FCM_KEY` env variable, see `--help`)

So unless you are only talking about broadcast messages then I think this is likely a problem of you having to build your own client.

**Comment by Hareet** [comment]
Thanks for opening up that issue related to broadcasts!

>Note that unless you are building your own app with your own FCM key, this won't work. Since the FCM key is tied to a particular app, you need to build / distribute the app yourself with your own FCM key

Yup, we've already done that.

>and configure the mailroom side appropriately. (MAILROOM_FCM_KEY env variable, see --help)
I'm hopeful this is all we will need. I'll open a PR with brief section in docs across the repos that will link together this information. Hopefully others will find it useful on how rapidpro (django + mailroom), fcm and relayer syncs work together.
