### ISSUE TITLE
Add fields to messages obtained through API

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#140]
We need to assign tags and other information to messages. These should be accessed through the API and stored in RapidPro.

For example, for at least minimal integration with case management, a case ID field would be helpful, although the rest of the case information can be in another system. Another example is annotations/notes, which are increasingly necessary for trac dashboards. Further, arbitrary tagging of messages would be useful, such as when using a webhook to categorize message content.

**Comment by citizenrich** [comment]
Just a postscript: this is not to say that much of anything should be stored in RapidPro, but at least minimal referencing information for other dashboard/case management systems.

**Comment by ericnewcomer** [comment]
We are actually building a case management tool for unsolicited messages sent to U-report at https://github.com/rapidpro/ureport-partners that is doing exactly this (including cases, notes, etc). (There's nothing there yet, the project is just getting underway). We can revisit this idea, but I expect this tool can be created without tagging messages in RapidPro, instead associating message ids with case information in the external system.

The aim is for RapidPro to not grow in complexity unless absolutely necessary. Labeled messages coupled with contacts, contact fields, and contact groups should get you what you need at the platform level to build tools like this. We really don't want messages themselves holding any additional state. Due to the scale we need to support at the platform level, we are very apprehensive of additional data at the message level.
