### ISSUE TITLE
Missing already translated Portuguese strings

### ISSUE THREAD

**Issue by paulobernardoaf** [rapidpro/rapidpro#1417]
- Hey guys, after we've updated our RapidPro instance to v6.0.0, we noticed that some Portuguese translations were missing in some cases. We've analyzed some commits made on the locale folder, between v5.7.79 and v6.0.0,  and discovered that these specific commits removed/commented some of the translations:

  - https://github.com/rapidpro/rapidpro/commit/c654e6e7b2162fb8a894e0600731e35cdf0e28ed
  - https://github.com/rapidpro/rapidpro/commit/4ab9e828046fb0282a69fcefd0ffba00bd539133
  - https://github.com/rapidpro/rapidpro/commit/d80bb776cc95854e17ca275125db9ece288876f8
  - https://github.com/rapidpro/rapidpro/commit/64f67a4379158277300ef79e20c4544751f0c30a

- Translations are also missing on Transifex, the percentage status was 100% a few months ago, after the update with this PR: https://github.com/rapidpro/rapidpro/pull/1306
But now they are back to around 75%.

- Are we missing/mislead in some aspect or was that intended to be removed for some reason? If so, could you guys explain why? If not, how could those translations be rolled back to the master branch somehow?

Thanks in advance.

**Comment by rowanseymour** [comment]
One of things we did as part of 6.0.0 was try to clean up localized strings to make it easier for translators. That involved:

 * Removing strings that don't actually appear in the UI. In the past we had a lot of localized strings on things like model fields which were not being used in the UI. We've gotten rid of most of those so that translators don't waste their time translating things that are never seen. For example from the diff of that first commit, strings like `The org this event is connected to` / `A organização com a qual esta mensagem está conectada`
 * Using `trimmed` with `blocktrans` template tags so that translations aren't lost everytime that there are whitespace changes which don't effect how the text is rendered, e.g. indentation changes.

So you can also see in that diff that strings like..

```
msgid "Your SignalWire channel is now connected."
"\n"	
"        Your SignalWire channel is now connected.\n"	
"        "
```

Become strings like..

```
msgid "Your SignalWire channel is now connected."
```

Unfortunately fixing those does break existing translations based on the whitespace that was there previously. But django's makemessages command keeps the existing translations around as "fuzzy" translations, so I think transifex will suggest the fuzzy translations when you try to translate the new trimmed strings.

So the bad news is that some of your existing translations map to strings that no longer exist, but the good news is that going forward, 1) you'll only be translating strings that are actually used and 2) they won't be lost everytime there are insignificant whitespace changes.

**Comment by paulobernardoaf** [comment]
Thanks for the detailed and fast explanation @rowanseymour!
We are going to translate it again to enter this new pattern.
