### ISSUE TITLE
Allow background flows to be used as campaign events

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1423]
Requires small change in mailroom. Maybe trickier part is how it works in the UI which currently looks like:

<img width="616" alt="Captura de Pantalla 2021-01-19 a la(s) 14 43 31" src="https://user-images.githubusercontent.com/675558/105084738-c697d200-5a64-11eb-995e-58a2dde9d068.png">

**Comment by rowanseymour** [comment]
Somewhat related it seems like Single Message flows should be implemented as background flows, tho still giving users the option to skip/interrupt/background

**Comment by ericnewcomer** [comment]
This interruption option was something cooked up because we didn't have background flows. I kind of want it to be implied that single message flows and background flows are implicitly handled as such. 

For the UI, the dropdown is slightly different in the messages case..

It currently shows, `Stop it and send the message` and `Skip the message`. We could update that to just be `Send the message` and "Skip the message". Of course this changes the contract for existing campaigns, but maybe that is okay?

In the flow case, the options would change based on the flow selected. If it's a background flow it'll say `Start the flow` and `Skip this event`. For interrupting flows, it'll have `Stop it and start this flow` and `Skip this event`. Perhaps that is too subtle?

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/3663
