### ISSUE TITLE
Flow not switching Channel when updating contact

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/rapidpro#1433]
There's a little problem when setting on which channel the flow should send a message, in this particular org there's 3 different WhatsApp channel, and even when updating the preferred channel to execute the flow it only send messages through the first channel on the channels listing.

To reproduce the error:
1. Create an Org
2. Add +2 WhatsApp Channel
3. Create a flow with _Update Contact_ setting a Channel that _isn't_ the first on the listing
    - The list that I mention is the one when you click on the Org's name
4. Test it with _Start Flow_
    - Using a trigger will 100% ignore the "Channel Setting" block and use the Channel that the user sent the keyword.
    
Then the "Update Contact" won't work, it will only send message via the channel that the user sent the first message, so if my first sent message was for "Channel A" the "Start Flow" will only sent me message through "Channel A" even when updating my contact via flow to switch to "Channel B".

**Comment by matmsa27** [comment]
Hi @rowanseymour , did you see anything like that?

**Comment by norkans7** [comment]
I think the problem here is that WhatsApp channel cannot initiate a message to a contact that did not send to it in the last 24 hours.

So Channel B cannot send a reply to a message that was sent to Channel A unless channel B also received a message from the same contact in the last 24 hours or use message templates.
