### ISSUE TITLE
Webhook authentication in headers

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#146]
Many webservices (... like RapidPro's API) use headers for sending authentication/authorization credentials. 

Allowing the configuration of authentication/authorization headers will enable faster and easier integration with external systems.

**Comment by ewheeler** [comment]
Org webhooks can now include user-defined headers (webhooks for org events configured on the Account Details page).

I think it would be valuable to add the ability to configure headers for Flow webhooks as well. This might sound crazy, but a valuable use-case I found using two flows:
1. a daily flow puts its respondents into several groups based on their responses
2. a flow later in the day sends an email summary of the day's group membership counts to relevant stakeholders

This could be implemented if flow number 2 could use a webhook (with auth headers) to lookup the group membership by hitting https://api.rapidpro.io/api/v1/groups.json?name=GroupA , https://api.rapidpro.io/api/v1/groups.json?name=GroupB , etc
It would also be amusingly meta to have rapidpro hitting its own API (aka rapidouroboros)

@nicpottier you mentioned [here](https://github.com/rapidpro/rapidpro/pull/149#issuecomment-85566727) some potential changes to Flow webhooks. any further ideas on that front now that rule-chaining is possible?

**Comment by nicpottier** [comment]
![yo dawg](https://i.imgflip.com/oa584.jpg)

So I don't think the group thing would actually work, since you'd quickly get into paging. There's also a part of me that is absolutely terrified at what people would do with it. (restart the contact down a flow, creating a loop?)

All that doesn't really mean that I'm not ok with headers, just maybe not ok with API calls. We are about to ship some big UI changes this weekend on the flow editor and I believe @ericnewcomer has thought a bit about where webhooks would belong there. So once that is out and stabilized this would be more easily possible.

**Comment by ericnewcomer** [comment]
First, I'd really like to +1 the yodawg.

I think what @ewheeler is describing would work. He's doing a separate call for each group which shows the membership count, so paging shouldn't come into play.

I think we do want to have header configuration in the flow webhooks. Yes, those dialogs are going to look a little bit different in the coming week. However, before we go too far down that path, we'll want to remove the webhook action since we really only want one way to do this (instead only using a webhook ruleset). That has some migratory implications, but should be manageable.

I share the same fear of rapidpro calling rapidpro creating the opportunity of an infinite loop, but that exists today, there just has to be an external server involved to accomplish it. Preventing that would require quite a bit more thought either way.

All that said, it feels super weird to call ourselves in a flow. I wonder if maybe instead we just make it possible to do @groups.my_group.members or something along those lines. This raises a whole other host of issues of course.

**Comment by nicpottier** [comment]
Ya, so, agreed we should add this for sure, but maybe wait until webhooks are refactored to be ruleset only?

I think @groups.my_groups.member_count or whatnot opens up a can of worms when it comes to being able to do things offline (and also in scaling in general). Having an assertion that the contacts in flows don't need to know about other contacts is a pretty big simplifying assumption that I don't think we want to break.

**Comment by ericnewcomer** [comment]
Ya the offline argument makes sense. It's much easier to exclude flows with webhooks from offline runs than it doing weird things with text replacements. I guess to that point, those would be empty strings in the offline world. But ya, very messy indeed.

**Comment by ewheeler** [comment]
@nicpottier @ericnewcomer BIG +1 on the yodawg

Both ways definitely have worms of their own. Getting group counts with the webhook route might be the nicer worms, as then its really clear to the flow author/user that such functionality will not be available in an offline flow context.

Makes sense to wait for the flow webhook refactoring in any case, so I'll keep an eye out for that

**Comment by johncordeiro** [comment]
Hey guys, I suppose the current state of flow editor is ready to receive custom headers on webhooks requests. Can we proceed with the PR @nicpottier @ericnewcomer ?

**Comment by ericnewcomer** [comment]
Yup! We'd welcome a PR for this. 

On a side note, we are in parallel working on a shmancy new flow editor which has this feature, but is at least a couple months out. So, depending on the demand, it may be worth waiting for that.

**Comment by teehamaral** [comment]
I think this issue can be closed.
