### ISSUE TITLE
Power BI Integration

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1467]
Hi everyone, and integration between RapidPro and Microsoft PowerBI to send data like a number of messages for a channel, flow executions, and any other information by an organization can be interesting. With this integration, will be possible to create a lot of dashboards on PowerBI and get power to the users analyze data about your organization, and take decisions.

Integration can occur like Chatbase integration. I open this issue to discuss with you guys the better way to implement this feature on RapidPro.

**Comment by rudigiesler** [comment]
Looking at https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources , looks like you can connect directly to the rapidpro postgresql database. This doesn't help for the managed instances like textit.

There's also the current org prometheus endpoint feature, which can be used with managed instances like textit.

If this is integrated like the Chatbase integration, then we should probably look at a way of having a generic integration with multiple backends, eg. If instead someone wanted to use something open source like Superset, then they just need to add a Superset integration.

**Comment by nicpottier** [comment]
I doubt the direct connection would work against our schema even if you did want to give full access to PowerBI, but ya, that's not really a tenable solution anyways.

@matmsa27 have you looked at all at what is required to become a PowerBI data source? Is there an SDK or the like available that you've seen?

**Comment by paulobernardoaf** [comment]
After a first analysis, we've found two ways of doing this. One of them can already be used, but we think that this one is not the ideal solution by far for the customers, since it requires a lot of manual tasks.

- Currently, PowerBi can already be used to gather information from RapidPro via the REST APIs that RapidPro offers, just need to copy the API Url, paste it on the PowerBi field, add the Authorization Header with proper credentials and that's it. The problem with this integration is that:

  - RapidPro uses pagination. With this case scenario to gather 1,000 users, for example, we would need 10 different Url copy/paste, one for each page. I've not found an easy way on how to automate this process, but if this automation is possible, this would not be a big issue.

  - If the customer wanted to gather all possible data from RapidPro, even without going through all pages, he would need to copy/paste every API Url to integrate. If we included the pagination issue, this would be impracticable.

  The pros of this integration are that technically is easy to use (to connect and gather simple data) and meet the needs of the integration.

- The other way that we've found out is creating an integration on PowerBi itself, [here's the start guide](https://docs.microsoft.com/pt-br/power-query/startingtodevelopcustomconnectors). With this integration, the customer would just click to add it on PowerBi, and the data would be gathered automatically after some basic configurations for authentication. I can't think if some newer endpoints on the RapidPro side would be needed to make this integration possible, but probably they will.

**Comment by nicpottier** [comment]
Thanks for the useful background! Ya, I would think a direct integration would likely be the right approach long term.

**Comment by rasoro** [comment]
Hello. We are developing a power bi custom connector, which provides data sources through the api, which are intended to be used in the power bi desktop to create dashboards and data visualization.

so we are creating this repository to share this possibility with everyone. https://github.com/Ilhasoft/custom-connector-powerbi

please, feel free to give us feedbacks to improves this connector.

![sscc1](https://user-images.githubusercontent.com/75167930/125677013-35cf9dc1-56bb-4f53-89f2-ab62f7e99471.png)
![sscc2](https://user-images.githubusercontent.com/75167930/125677031-4c10eec8-d986-4129-bd6c-6896986715fb.png)
![sscc3](https://user-images.githubusercontent.com/75167930/125677040-293089f4-02cd-4ce7-81a2-ea31f8472f5a.png)
![sscc4](https://user-images.githubusercontent.com/75167930/125677046-778442a8-890d-4de7-a9c0-748c9d60f738.png)
