### ISSUE TITLE
Viber's Keyboard feature request

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/rapidpro#1491]
The Viber's API allows to customize the _quick reply_ button via a _JSON Payload_, for example:
```json
{
	"Type": "keyboard",
	"Buttons": [{
		"Columns": 3,
		"Rows": 2,
		"Text": "<font color=\"#494E67\">Smoking</font><br><br>",
		"TextSize": "medium",
		"TextHAlign": "center",
		"TextVAlign": "bottom",
		"ActionType": "reply",
		"ActionBody": "Smoking",
		"BgColor": "#f7bb3f",
		"Image": "https: //s12.postimg.org/ti4alty19/smoke.png"
	}]
}
```

The above example is shown at [Viber's Keyboard Example](https://developers.viber.com/docs/tools/keyboard-examples/), a client came with this request, this feature would be implemented in specific flows that uses _quick replies_.

**Comment by nicpottier** [comment]
This should be something that can be added on the Courier side of things when sending a Viber message. (quick replies are an attribute of the message) We'd accept a PR to make those changes there.

**Comment by rafaelbreno** [comment]
@nicpottier where could this feature be implemented? I thought about two options:

1. At the channel setting  could be added a option (Viber > Custom Quick Replies) to implement the JSON showed on Viber's API and it could be "selected" on the tab "Quick Replies" in the FlowEditor. I think this solution would need to modify: RapidPro, FlowEditor and Courier

2. You said that this could be done on Courier, how?  I think could be added some new fields into Viber's Channel like Flow, Flow Card with the custom JSON, but how it would be implemented? The Viber's keyboard would be a custom made button, so would be nice to allow the user to customize it by themselves, or would need to do something via shell?

**Comment by nicpottier** [comment]
Quick replies are agnostic to channel types, the editor / mailroom will include quick replies in the Msg payload passed to Courier if it is set in the flow. So Courier should just be modified to make the appropriate calls to Viber when there are quick replies set on the msg.

**Comment by matmsa27** [comment]
To add information, Telegram supports the [personalization](https://core.telegram.org/bots/api/#replykeyboardmarkup) on quick replies.

I agree with you @nicpottier this can be implemented on the courier side. My only doubt is when is configured a number of quick replies in a send message card, and in another card was configured other number for quick replies, maybe the layout defined on config channel doesn't look good for differents numbers for the quick reply, because it will use the same layout for all messages. The size of the words of the quick replies can be a problem too when showing on application (Telegram and Viber).
