### ISSUE TITLE
FlowRun modified_on greater than exited_on

### ISSUE THREAD

**Issue by evansmurithi** [rapidpro/rapidpro#1521]
Hi, This is more of a question than a bug. Is it possible for the `modified_on` field of a `FlowRun` to be greater than the `exited_on` field? If so, what would be the causes for such a scenario to occur?

**Comment by rowanseymour** [comment]
If it's a small difference then it's probably the difference between when the run exited in the engine (`exited_on`), and when that change was written to the database (`modified_on`). Which is intentional since we want `modified_on` to always reflect when changes become visible in the database.

(Usually the [mailing list](https://groups.google.com/g/rapidpro-dev) is a better place for questions like this)
