### ISSUE TITLE
Flow wait that accumulates inbound messages

### ISSUE THREAD

**Issue by rasoro** [rapidpro/rapidpro#1535]
Some users when creating flows want a time to wait for a response of less than 1 minute. For example, when building a flow sometimes the user needs to accumulate responses and go to the next node waiting less than 1 minute after the user finishes responding, waiting more than 1 minute looks strange to the user.
To exemplify, imagine the following flow as an example of the accumulation of responses.

![example_accumulate](https://user-images.githubusercontent.com/75167930/126185511-b28e5f43-f6c5-4b3f-984e-7a721af92902.png)

**Comment by ericnewcomer** [comment]
One way you could accomplish this is loop into the same wait and append their input to a result. Then proceed through the flow via No Response. Effectively the inverse of what you have here. But ya, I'm pretty sure what you describe here can be modeled with the tools that exist today.

We've seen that pattern before except they waited until the user sent back "done" to allow them to write a giant message that was stitched together via Save Flow Result. But ya, no reason you couldn't do the same thing using No Response after X minutes instead.

**Comment by rasoro** [comment]
Do you have suggestions how to solve this situation in a native feature on flow editor? Enable options for `Continue when there is no response` less than 1 minute is an option here?
Because waiting for the user to send some command to exit the accumulation loop conflicts with our need to create a more natural conversation.

**Comment by ericnewcomer** [comment]
It seems you either want to have a window and accumulate the messages your you want to proceed. If you don't want to rely on a keyword to break out, then in the cases you want to accumulate message you would proceed after a minute. I'm not sure why we'd need a case for waiting long enough for accumulation to occur but is also less than a minute of quiet.

I should also say more directly that I don't think we want to decrease the timeout below 1 minute as that is not something we can (or want to) sign up to honoring in real time.

**Comment by matmsa27** [comment]
Hi Eric, in some cases to have real-time, the user wants 30 seconds, another user 45 seconds, and another user 1 minute. Depends on the context the flow and the organization that the user is building. To depend on the keyword to accumulate messages and scape is not a good option. In this case, the chatbot depends on a user's action to go ahead. The idea is to the chatbot appear more human to make decisions alone.

We can do this via environment configuration. For example, the mailroom will have a variable that corresponds to the minimum value/time available on `Continue when there is no response`, and with this environment variable, the flow editor can get this value and show more options to the time value. To be more clear, I can define the environment variable on mailroom to 30 seconds, the flow editor gets this value when the flow editor loads and shows times like 1minute, 55 seconds, 50 seconds, 45 seconds, etc (we can decide the interval time, can be another variable too) until 30 seconds that was the value configured on the variable environment on mailroom. To default value, we set up 60 seconds and the flow editor and the behavior on rapidpro follow the same way today.

What do you think? with this, we can enable more time options to who hosts rapidpro to their chatbots appear more human to the users that create chatbots. The hosts that will update with this will not suffer because nothing changes using the default value.

**Comment by ericnewcomer** [comment]
@matmsa27 This issue, while named after a suggested implementation, is actually for discussing a feature around accumulating messages. 

The issue for delays so chatbots can appear more human is #875.

**Comment by ericnewcomer** [comment]
We had a bit of a powwow on this morning so capturing what came out of that discussion.

* We do indeed see this as a sister feature to #875. That feature deals with outbound waits, while this one deals with inbound waits.
* Courier has and likely always will handle messages as quickly as they arrive. This is a flow handling feature which points to a mailroom implementation. In mailroom we would need to adjust handling of messages to be buffered across as many messages that arrive during a specified quiet period. 
* One thought is expressions may access concatenated text/attachment using the usual `@input` attributes and we could consider adding  `@input.messages` to access the individual messages if desired.
* Messages handled together need to be designated as such at the db level so this could be surfaced by the UI where appropriate
* Where this is configured is TBD. It could be at the wait level, the flow level, or the account level, or a combination of the three with defaults.

**Comment by matmsa27** [comment]
Hi @ericnewcomer , could you explain in more detail the last point, please? For me it's no clear what is TBD, and what levels are you talking about, is it about time in flows and in the channel?

**Comment by ericnewcomer** [comment]
Just that we haven't decided where and how much configuration to allow at this point. We do aim to allow flexibility, but not at the expense of simplicity. 

The point here is that that bit is not a huge concern. We were mostly just hashing out how the core feature should work.
