### ISSUE TITLE
Sending Bulk sms with infobip API

### ISSUE THREAD

**Issue by wakashela** [rapidpro/rapidpro#159]
Hi Guys,
I am hacking around rapidpro, to manually add infobip API as an external API.
I want to override number masking since i already know its not supported by infobip, and since i want to use rapidpro in sending only not receiving. why do i need it for sending only? is simply because i will be receiving phone contacts from a third party since rapidpro has APIs for adding contacts that's a big help for me. But when it comes to sending bulk sms i would like to use a third party like infobip sending my sms with labels not masked phone numbers, I really appreciate the job you have done guys in building an amazing robust sms platform.How do i go about solving this particular scenario?

**Comment by nicpottier** [comment]
We already support InfoBip:
  https://github.com/rapidpro/rapidpro/blob/master/temba/channels/models.py#L1012

So really the only bit you are changing is that you are trying to use it as a bulk sender, which ya, we don't support because you can't mask the number.

I would look at the Nexmo channel as an example of how to change InfoBip into a bulk sender on your install.
