### ISSUE TITLE
Test environment set up

### ISSUE THREAD

**Issue by rudigiesler** [rapidpro/rapidpro#163]
I'm having a bit of trouble setting up a test environment and getting all the tests to pass. I haven't been able to find instructions on getting a test environment set up in the documentation.

The steps taken are as follows:

1. Follow the documentation to get a dev environment set up (Able to run the server)
2. Add the extensions `postgis`, `postgis_topology`, and `hstore` to the `template1` database.
3. Run `python manage.py test`

The testing fails with 9 errors and 14 failures.

Travis-CI config: https://github.com/praekelt/rapidpro/blob/feature/issue-3-add-travis-ci/.travis.yml
Output of test failure: https://travis-ci.org/praekelt/rapidpro/builds/59359519

**Comment by ewheeler** [comment]
hey @rudigiesler 
i noticed this too. theres a related discussion here: https://github.com/rapidpro/rapidpro/pull/149#issuecomment-93982541

and this commit will add these extensions via migrations to make it easier to run tests: https://github.com/ewheeler/rapidpro/commit/275e4eeb8e26898fa5877f9dbec2908e7497f354

**Comment by nicpottier** [comment]
@ewheeler It looks like he knows the extension piece as rudi mentioned updating the postgres template.

@rudigiesler I wonder if your branch is just out of date. I'm trying your Travis file on our RapidPro fork to see if I get similar errors.

**Comment by rudigiesler** [comment]
@nicpottier Merging in the latest changes from rapidpro/master doesn't seem to have any effect. The same tests are still failing locally for me.

**Comment by nicpottier** [comment]
Hey @rudigiesler ..

I played with this a bit and got a build passing here:
  https://travis-ci.org/nyaruka/rapidpro/builds/59406120

A few things changed:
 * I'm not running the temba/perf_tests, which do have an error in them, but really we don't want running on every build because they are slow
 * I put in a step to symlink the dev settings.
 * To get a cleaner output from coverage, we're being explicit about the tests run. You can check the .travis.yml in nyaruka/rapidpro (used yours as a base) to see the packages we're running.

I'll get the perf test passing in a sec and push that to rapidpro as well.

**Comment by rudigiesler** [comment]
Issue resolved in https://github.com/rapidpro/rapidpro/pull/166
