### ISSUE TITLE
Support to languages that are not in pycountry lib

### ISSUE THREAD

**Issue by paulobernardoaf** [rapidpro/rapidpro#1637]
Hey Guys, have you ever needed to give support to a language that is not in `pycountry` lib?
Currently, we are looking for a way to add the [Akatek language](https://en.wikipedia.org/wiki/Akatek_language), which doesn't have an ISO 639-1 code, and the ISO 639-3 code is `knj`.
The pycountry lib doesn't have a country with this `alpha_3` code.

**Comment by rowanseymour** [comment]
We made a change a while back to restrict what languages we expose to users, because whilst it's great to allow users to accurately describe what languages they are using in flows, things get complicated when external services (channels, NLP services etc) haven't heard of those languages. Is there a reason pycountry doesn't have this language? Can we get support added there first?

**Comment by paulobernardoaf** [comment]
From what I've seen, the pycountry lib doesn't accept any new languages because it follows the ISO standard using the pkg-isocodes database from Debian.
Source: https://github.com/flyingcircusio/pycountry#data-update-policy

**Comment by rowanseymour** [comment]
So then we need to ask why isn't it being added there
