### ISSUE TITLE
Imports with new conversation triggers missing channels fail

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1641]
Giant import was failing and tracked it down to this, which when removed imported without issue.

```json
{
      "trigger_type": "N",
      "flow": {
        "uuid": "5d8f4e75-eb05-463d-b572-70761ec4ee7f",
        "name": "New Ticket Flow"
      },
      "groups": [],
      "exclude_groups": [
        {
          "uuid": "342a1d53-f7a7-4efc-a5c5-e1324c3f6f6d",
          "name": "Open Tickets"
        }
      ],
      "channel": null,
      "keyword": null
    }
```

**Comment by rowanseymour** [comment]
This is a _New Conversation_ trigger and the problem is that that type supposedly requires a channel to be set, and fails if you try to import one without the channel set. But seems like channel could be made optional.. and while we're in there, make channel an option for all trigger types https://groups.google.com/g/rapidpro-dev/c/hW0RK9Shd4U/m/k4qBKiSPCQAJ?utm_medium=email&utm_source=footer

**Comment by rowanseymour** [comment]
However... I'm now poking around the code and seeing why channel is currently required for this trigger type - when we create such a trigger we activate it against the given channel, e.g. you create a New Conversation trigger for your Facebook channel, it is going to call the FB API call_to_actions for that channel.

It seems we could do that for channel types that support new conversation events when you add the channel.. just let courier create the channel events, and mailroom handle them even if it doesn't find a `New Conversation` trigger type.

For now maybe the fix is making imports work partially - import what they can, report back what they can't.

**Comment by rowanseymour** [comment]
We now ignore such triggers on import
