### ISSUE TITLE
Possible issue in task to update WhatsApp tokens

### ISSUE THREAD

**Issue by pauloabreu** [rapidpro/rapidpro#1654]
## Introduction

Has a Celery task called **refresh_whatsapp_tokens** (this task can be found at temba/channels/types/whatsapp/tasks.py).
Sometimes the .save() method on end of task does not work, has no exception or error in logs,.

## Have we a problem?
The http_log is created with new auth token, the method save() is called with succes according with code, but when we check the **auth_token** in config field has not changes.
We created some Google Sheets with these Channels and comparing these Channels before and after the task we found this issue.

## Code
Part of code
```
for channel in Channel.objects.filter(is_active=True, channel_type="WA").order_by("id"):
            try:
                url = channel.config["base_url"] + "/v1/users/login"

                start = timezone.now()
                resp = requests.post(
                    url, auth=(channel.config[Channel.CONFIG_USERNAME], channel.config[Channel.CONFIG_PASSWORD])
                )
                elapsed = (timezone.now() - start).total_seconds() * 1000

                HTTPLog.create_from_response(
                    HTTPLog.WHATSAPP_TOKENS_SYNCED, url, resp, channel=channel, request_time=elapsed
                )

                if resp.status_code != 200:
                    continue

                channel.config["auth_token"] = resp.json()["users"][0]["token"]
                channel.save(update_fields=["config"])
```

## Tests

- We tried use transaction.atomic() to save instead only save(), the problemns ocurrs.

- Verified if this task cause some exception, nothing found.

- Verified if request before save is ok, this request return the token and 200 status code, is working ok.

- We changed the time of task to run each 10 minutes, and everything worked fine.

- We tried manually call the task, everything worked fine.

Maybe this problem can be caused by JsonField, but we did not this test.

### Sugestions

We open this issue to get some sugestion/resolution or any idea to solve this.

Reference: https://github.com/rapidpro/rapidpro/blob/main/temba/channels/types/whatsapp/tasks.py

**Comment by rowanseymour** [comment]
I would strongly suspect it's not a problem with Django's `Model.save()` but a case of it not being called.. do you have an example of an http log you can share?

**Comment by matmsa27** [comment]
Hi @rowanseymour we cant share a `http_log` object because the are sensitive data about tokens. There are interesting points about this:
- When changed the schedule the task to run for each 10min, everything works fine
- When the task run, the object for `http_log` is created correctly, the exception is not raised and looks that `.save()` method worked as well. But when we check the config, the data about `auth_token` is different for the data saved on `http_log` object.

My point is, there is any possibility there is any behavior strange on postgres (we are using the postgres version 11), or the json field used for the `config` column on `channel` object?  What your thoughts?

**Comment by rowanseymour** [comment]
All I can say is that this isn't an issue we've seen. The supported versions of Postgres for latest RapidPro are 12 and 13, tho we also didn't see this issue with Postgres 11 in the past. It's always possible something is broken but this will have to be something that you guys investigate more because we're not seeing the problem on our boxes.
