### ISSUE TITLE
Absolute time limit for sessions

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1663]
We've noticed quite a few runs accumulating that archiver can't archive even tho they haven't been modified in over 90 days. They're still active because they are parent runs of child runs where the contact is typically in a never-ending loop. We currently have limits on sprints per session and steps per sprint so these child runs will eventually fail, causing the parent to fail too.

But even with those limits, a contact can end up in the same flow for a very long time - for example a wait with a 1 week timeout, the exit from which is routed back into the wait.

So maybe if long-running sessions are a thing we definitely don't support, should have an absolute limit on the the number of days a session can last before it's failed. If it was 90 days, that would ensure runs are never stale for longer than 90 days and can always be archived.

**Comment by rudigiesler** [comment]
From our side, there is just a single use case that I can think of for longer running flows.

In order to take advantage of the 24 customer interaction window on WhatsApp, a pattern that we often use is to send the user a message, that has a call to action, so that they will send some kind of message back to us. After they send a response, 23 hours later we send them the next message in the series, also with a call to action, and that loop continues.

This is so that we don't overload them with a lot of information all at once, and also so that we don't have to rely on template messages for these multi-day interactions.

The way we've currently got this implemented on one of our projects is to have a "wait for user response" with a timeout, and we use the timeout branch to go on and send the next message (there's a lot more logic in there to handle additional user messages being received in the wait time).

This implementation has its advantages, we can very easily set up these multi-day messaging flows by having a child flow "wait for 23 hours" that we can use the "enter a flow" action with, so you just have message, child flow, message, child flow, etc, making content management easy.

It does have a big disadvantage though, and that is that we have to be very careful about interrupting users in existing flows, because that will break their messaging stream.

The other way we thought about doing this is through triggers, but then you have to have contact fields to remember which set of messages, and which message in that set, they are currently on. And then you also have to have more complicated content flows, because they have to branch to the correct message, and update the contact fields accordingly. But it does solve the flow interruption issue, so that might be worth the extra complication.

Currently none of these flows are anywhere near 90 days, but I thought I'd put forward this use case as one of the possibilities for wanting flows to be able to run for long periods of time.

**Comment by ericnewcomer** [comment]
I would prefer to see a world where we modeled ongoing opt-ins to manage this case. Facebook is testing an API due out later this year for managing daily, weekly, and monthly outbounds with on-going opt-in (for messenger, not WA, but there are parallels here). The example you shared honestly sounds closer to that than it does a justification for long running flows.

**Comment by rudigiesler** [comment]
Yes I would agree with that, the above is just a workaround to deal with the customer service window and templated messages. Once there's a proper way of dealing with this, then it becomes a lot easier to deal with, and rather put it into something like a campaign.
