### ISSUE TITLE
Ability to create group names dynamically

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#187]
Previously, contacts could be added to groups based on flow variables (e.g., ```@flow.district.category``` or ```@step.contact``` which would add contacts to a group with a name based on the result of the variable evaluation)

However, the flow editor UI now complains that there is no match found for expressions like @flow.district.category and will only allow the user to cancel or close the dialog.

Attempting to add a contact to a dynamic group using advanced expressions (like ```=(UPPER(contact))```) is allowed by the flow editor UI, but results in the creation of a group with a name that is the literal expression (in this case a group called "=(UPPER(contact))")

**Comment by rowanseymour** [comment]
Seems both `AddLabelAction` and `AddToGroupAction` only treat strings beginning with @ as expressions, i.e.
https://github.com/nyaruka/rapidpro/blob/master/temba/flows/models.py#L4056
https://github.com/nyaruka/rapidpro/blob/master/temba/flows/models.py#L3952

Would be good to have both of those actions record an error to the action log if the expression can't be parsed so that we don't end up with labels and groups with unparsed expressions for names, and the simulator can show the user a meaningful error to report that the expression is invalid.

**Comment by ewheeler** [comment]
Yup this used to work for group names if the string began with @ 
But the UI no longer allows you to save a group name that you've entered that starts with a @ -- it does allow names that being with =, but does not evaluate

**Comment by nicpottier** [comment]
paging @ericnewcomer as this is likely a regression from the new editor changes.

**Comment by ericnewcomer** [comment]
Yup, @nicpottier is right. This is from the new split editor changes that was shipped last week. I'll look into getting a fix for it out today.

**Comment by ewheeler** [comment]
@ericnewcomer thanks!
