### ISSUE TITLE
Dynamic Groups based on names don't re-evaluate

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#224]
Repro steps:
1) Create a search for "Judy"
2) Save as a new group "Judies"
3) Update a contact to have the name "Judy"

The dynamic group Judies doesn't have the contact saved in step three. Presumably this is because only groups based on contact fields are checked for re-evaluation.

**Comment by dodobas** [comment]
There are many occasions when a dynamic groups might be updated: on contact create, on import, flow execution, channel handlers, contact field updates. From what I could find those are using `Contact.handle_update` method which will reevaluate_dynamic_groups: https://github.com/rapidpro/rapidpro/blob/master/temba/contacts/models.py#L786

For example, `Contact.set_field` will call `handle_update` which is enough to update dynamic groups, but it will also check if we are importing, and in that case will not call `handle_update`. I am worried that there are other switches that prevent `handle_update` to be executed. The `handle_update` method will update `Events` so I guess that we should not call `handle_update` all the time.

The solution is to add something along the lines of `obj.reevaluate_dynamic_groups()` in `post_save` method in ContactCURDL.Update view. But I am not sure if that is what we want to do becuse that will not trigger Events. For example,
in the `post_save` method call `.update_urns` will in the end call `handle_update` (https://github.com/rapidpro/rapidpro/blob/master/temba/contacts/models.py#L1792) which might trigger events. 

What should we do in this case?

**Comment by nicpottier** [comment]
I think the reason for the odd treatment around handle_update and imports is that if you importing lots of fields then it gets expensive to reevaluate the contact's dynamic fields over and over rather than just doing it once after all the fields have been set.

We do need to update events after a name change (as well as reevaluate dynamic groups dependent on name) because the events may be based on the group that they are dynamically being added to.

Why is calling `handle_update` not a good option in `post_save`? Is it just that you weren't sure that Events should be possibly reevaluated in that case?

**Comment by dodobas** [comment]
Yeah, I was not sure if Events should be reevaluated

then I'll use `obj.handle_update(attrs=(Contact.NAME,))`, and write tests for this specific use case, since it is not picked up by tests

**Comment by nicpottier** [comment]
Ya that seems right. While we are at it, what happens when an import or API changes a contact's name? Are there other attributes that can be updated there that are also being missed?

**Comment by dodobas** [comment]
closing this issue as it's no longer valid, we no longer support creating dynamic groups with search expressions containing a `name ~ "a name"` or `id = 123` filters
