### ISSUE TITLE
Adding credit and sms plans

### ISSUE THREAD

**Issue by EswarSakamuri** [rapidpro/rapidpro#243]
How can we add credit? At present we are having 1000 credits, if I want to add more credit how can I add that?

Now by default RapidPro can send 30sms/hr if I want to make it to 60sms/hr how can I do that?

**Comment by wwwnizar** [comment]
you must log in as administrator

**Comment by srugano** [comment]
I'm experimenting with RapidPro and has created a superuser the Django way, but when I try to log in ( http:/myrapidpro.com/users/login/) in order to add credits to organization, it doesn't allow me to pass the login. And I've tried with 2 superusers accounts. Any hint of what's may be going on ?

**Comment by wwwnizar** [comment]
try to log to postgres database and giv the user superuser rights 0 to 1 




NIZAR GUESMIcomputer security expert
analyst-developer
GIS-WEBCIMSPcomputer center 
of ministry of health
 

    Le Vendredi 25 mars 2016 9h23, RUGANO <notifications@github.com> a écrit :
 

 I'm experimenting with RapidPro and has created a superuser the Django way, but when I try to log in ( http:/myrapidpro.com/users/login/) in order to add credits to organization, it doesn't allow me to pass the login. And I've tried with 2 superusers accounts. Any hint of what's may be going on ?—

**Comment by EswarSakamuri** [comment]
I made is_superuser in auth_user from f to t still I didnt get add credits after clicking organization name. Where should I change?

**Comment by wwwnizar** [comment]
![capturera](https://cloud.githubusercontent.com/assets/11974576/14201136/d117f492-f7e7-11e5-97c7-0243a439f615.JPG)

**Comment by wwwnizar** [comment]
Click on Topups

**Comment by EswarSakamuri** [comment]
Not able to get that option

![screenshot from 2016-04-01 13 43 08](https://cloud.githubusercontent.com/assets/10355920/14201467/be9892f4-f80f-11e5-9ab7-5484ffcb6374.png)

**Comment by EswarSakamuri** [comment]
Go this thank you so much guys for your support and time

**Comment by markotitel** [comment]
@EswarSakamuri can you explain how you got it?

**Comment by pangoSE** [comment]
> try to log to postgres database and giv the user superuser rights 0 to 1

Could you add this setting a user as superuser to the documentation?
