### ISSUE TITLE
Add channel type for Junebug

### ISSUE THREAD

**Issue by hodgestar** [rapidpro/rapidpro#256]
It would be good to have a channel type for connecting to Junebug (http://junebug.readthedocs.io).

Some questions:
- Looking at #229, it looks like a channel type must be either USSD or not USSD? Is that true, and if so, any thoughts on how to relax that requirement so that an instance of a channel can be of different types?
- #229 has quite a few changes (because its adding USSD support to). Is there a better PR to look at for the minimal set of things that need to be touched to add a new channel?

**Comment by nicpottier** [comment]
Junebug support would be great. A really similar PR for adding an SMS channel would be this one for Jasmin (don't mind the PR title :) ):
   https://github.com/nyaruka/rapidpro/pull/610

Mostly it is just a matter of adding in some UI bits, a handler for incoming messages / status etc, and a method to do the sending of messages. Wish it was a bit more object oriented but truthfully hasn't been a problem so whatever. :)

Right now the "type" that a message has is encoded within the channel it is associated with, so you can't really have a channel that does more than one thing because we wouldn't know how to send it. (as ussd or as text) Given the ever widening number of channel types that seems fairly reasonable, though USSD isn't even merged in yet, so maybe we'll hate it once it is.

In any case, yes, you'll want two channel types if you want to support USSD as well, you can reuse a lot of that code though and just switch on the channel type.

**Comment by hodgestar** [comment]
Thanks! We can focus on just adding support for SMS to start with and worry about USSD after that lands.

**Comment by nicpottier** [comment]
fixed in https://github.com/rapidpro/rapidpro/pull/435
