### ISSUE TITLE
Flows without messages don't decrement topups

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#347]
The rulesets during the execution of the flow register a considerable amount of information into the database. In flows with many runs and many rulesets, the system may have an overload because of these operations. 

Would it interesting that the rulesets also had the operation to decrement the credit of the organization?

**Comment by ericnewcomer** [comment]
It's true, only messages affect the credits for an organization. There's been some discussion over having that apply to FlowStep instead of Msg. But to date, we've felt comfortable modeling volume by messages sent as that is the primary goal of the platform, doubly so since IVR interactions are modeled as messages as well.

**Comment by nicpottier** [comment]
I don't think we are going to change this, credits are messages for the time being.
