### ISSUE TITLE
Display the contact's preferred channel on /contact/read/

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#371]
Currently possible to discern channel preference from message icon rollovers, but might be helpful to make it more visible.

**Comment by rowanseymour** [comment]
So currently we list the URNs in order and if the URN is..

  * Sendable: clicking opens the Send Message dialog for that URN
  * Not sendable: 
    - Mailto: an email link
    - Twitter: a profile on twitter.com
    - Other: no link

I don't think we have a lot of Twitter users these days and we're always talking about getting rid of mailto URNs.. so maybe we ditch linking to external sites, and simply this list so that if the URN is a link, it's sendable.
