### ISSUE TITLE
Token not displayed on /api/v2 when user is logged in and navigates to it via their browser

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#407]

**Comment by rowanseymour** [comment]
Not yet able to replicate this, even logging in to same account as in your screen capture. Are you logged in as real user when this happens, or servicing an org?

**Comment by ycleptkellan** [comment]
Thanks for looking at this. Yes, real user. Created a new account and am getting the same behavior; perhaps I'm missing something. Sending you a screencast.

**Comment by rowanseymour** [comment]
Have investigated and this isn't specific to the API but occurs when a user manually navigates to a non-SSL URL. Because we use `SESSION_COOKIE_SECURE`, login sessions don't extend to URLs which aren't `https://...`. If a user is authenticated but navigates manually to a `http://...` URL, they won't be logged in at that URL.

We could redirect non-SSL API requests to their SSL equivalents - like how we do with the login page. @nicpottier thoughts?

Either way this is an issue with our deployment and not the rapidpro code so let's close this issue and if do decide to change something we can create a new issue at nyaruka/utils.
