### ISSUE TITLE
Add IVR redirect action

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#494]
This would allow IVR calls to forward calls to a real person.

**Comment by rowanseymour** [comment]
Let's do this. I think we just need..

* An action called something like `forward_ivr` / `redirect_ivr`
   - Takes a URN (in the editor can be surfaced as just a phone number)
* Generates an event like `ivr_forwarded` / `ivr_redirected` which contains the URN
* Mailroom handles by generating a `<Dial>` command https://www.twilio.com/docs/voice/twiml/dial

**Comment by nicpottier** [comment]
So one thing that is interesting is that Dial isn't a terminal action in the TWIML universe. So this probably needs an associated split as well, at least for the case that the callee didn't pick up or they did.

**Comment by rowanseymour** [comment]
Hmm well that makes it all a bit more complicated - at least with my limited understanding of how our IVR stuff works!

That would mean we need a new wait / resume type no? I.e. the engine emits the `ivr_forwarded` event, then hits a wait and hands back control to mailroom. Mailroom handles the `<Dial>` command and then later resumes the flow session with something to tell the engine the other call didn't happen or it did.

**Comment by nicpottier** [comment]
Ya, I think we would need a new wait/resume. That said, maybe we just start with the action, that's still moving in the right direction.

**Comment by rowanseymour** [comment]
If I'm understanding the Twiml/NCCO docs correctly, the `<Dial>` / `connect` commands are both synchronous.. so if we had an action, and it wasn't terminal, then the flow continues after the forwarded call has ended (or failed). So for example the following actions..

```jsonl
{"type": "forward_ivr", "urn":"+123456789"}
{"type": "say_msg", "text":"Goodbye"}
```

Generate the following twiml..

```twiml
<Response>
  <Dial>+123456789</Dial>
  <Say>Goodbye</Say>
</Response>
```

And the only limitation is that the flow has no way of knowing if the forwarded call actually happened. Are we cool with that?

**Comment by fredygamez** [comment]
I have this requirement, I have been figuring out about the redirect and what happens sending the TwiML instruction. My suggestion is to transfer the call if answered, otherwise finish the call, as shown in detail in the following stackoverflow link [Twilio call transfer from in-call], using the **hangupOnStar** that tells Twilio to disconnect the caller (Field) from whoever they `<Dial>`ed (the conference), but still makes a request to the URL defined in the `<Dial>` verbs action attribute. 

https://stackoverflow.com/questions/17581902/twilio-call-transfer-from-in-call

Using `<Conference>` in this scenario gives you more flexibility to manipulate each leg of the call independent of the other than you would have if you use `<Dial>` to connect Field and Agent1.

So now Agent2 calls Field. Agent2 would go through the same process, just in reverse. Agent2 would get dialed into a `<Conference>` (lets call it ConferenceB) and your system would use the REST API to call Field. When Field answers they get <Dial>ed into the same conference as Agent2. Again, the system will need to grab the CallSid's of both Agent2 and Field, as well as the Sid of the `<Conference>`, persist them in some type of storage to use later.

Now, Field needs a way to tell the system to connect Agent2 with Agent1. To do that you can utilize the `<Dial>`s **hangupOnStar** attribute in the TwiML you hand Twilio when you dial Field into the ConferenceB. The <Dial> verb would look something like:

```
<Dial hangupOnStar="true" action="[process_hangup_url]">
    <Conference>ConferenceB</Conference>
</Dial>
```

hangupOnStar tells Twilio to disconnect the caller (Field) from whoever they `<Dial>`ed (the conference), but still makes a request to the URL defined in the `<Dial>` verbs action attribute. That is important because when Field needs to tell the system to redirect Agent2 into the ConferenceA with Agent1, and the request to the URL in s action attribute gives the system the opportunity to prompt Field to see if thats what he wants to do. So you might have Twilio execute some TwiML like this:

```
<Response>
    <Gather action=[gather_handler]>
        <Say>Press 1 to connect this caller to another<Say>
    </Gather>
</Response>
```

Hope that helps to solve details pending handling the voice flows.

**Comment by fredygamez** [comment]
I propose an idea of this GUI box interface that also includes a lay audio before forward, thinking about the use of TwiML elements. `<dial>` , `<say>`  and now `<play>`, to allow the logic in the flow options to inform users what happens if call is or is not connected. 

![image](https://user-images.githubusercontent.com/17584642/103859495-21eebb00-5088-11eb-9f38-5424a429ed1d.png)

**Comment by nicpottier** [comment]
If people wanted to play a message or use a say they would just use the normal actions for that then use the forward call action.

**Comment by rowanseymour** [comment]
Want to try sketching out how this all would work in the engine.. so just writing this as it comes to me!

* A new wait type `redirect`
* A new resume type `redirect_ended` with a `status` property 
* The new wait type can only be resumed by the new resume type (i.e. no run expirations during redirection, no wait timeouts)
* Resumes are now accessible in expressions via `@resume` in the same way that some properties of triggers are accessible via `@trigger`. For now only `type` and `status` are exposed.
* If the Twilio IVR forwarding succeeds, session is resumed with `{"type": "redirect_ended", "status": "success"}`, otherwise with `{"type": "redirect", "status": "failed"}`

```json
{
  "uuid": "11a772f3-3ca2-4429-8b33-20fdcfc2b69e",
  "router": {
    "type": "switch",
    "wait": {
      "type": "redirect",
      "phone": "@globals.agent_tel_en"
    },
    "categories": [
      {
        "uuid": "2ab9b033-77a8-4e56-a558-b568c00c9492",
        "name": "Success",
        "exit_uuid": "3bd19c40-1114-4b83-b12e-f0c38054ba3f"
      },
      {
        "uuid": "c7bca181-0cb3-4ec6-8555-f7e5644238ad",
        "name": "Failure",
        "exit_uuid": "9ad71fc4-c2f8-4aab-a193-7bafad172ca0"
      }
    ],
    "default_category_uuid": "5ce6c69a-fdfe-4594-ab71-26be534d31c3",
    "result_name": "Redirect 1",
    "operand": "@resume.status",
    "cases": [
      {
        "uuid": "e27c3bce-1095-4d08-9164-dc4530a0688a",
        "type": "has_any_word",
        "arguments": ["success"],
        "category_uuid": "2ab9b033-77a8-4e56-a558-b568c00c9492"
      },
      {
        "uuid": "e27c3bce-1095-4d08-9164-dc4530a0688a",
        "type": "has_any_word",
        "arguments": ["failure"],
        "category_uuid": "2ab9b033-77a8-4e56-a558-b568c00c9492"
      }
    ]
  },
  "exits": [
    {
      "uuid": "3bd19c40-1114-4b83-b12e-f0c38054ba3f"
    },
    {
      "uuid": "9ad71fc4-c2f8-4aab-a193-7bafad172ca0"
    }
  ]
}
```

That would save a result `@results.redirect_1` like..

```json
{
  "input": "success",
  "value": "success",
  "category": "Success"
}
```

### Alternative 1

* Instead of a single resume type, we have `redirect_ended` and `redirect_failed`. The former includes information about the call, e.g. 

```json
{
  "type": "redirect_ended",
  "redirect": {"duration": 30, "recording": "https://example.com/324.mp3"}
}
```

### Alternative 2 (similar to the classifier approach)

* Instead of exposing `@resume` in expressions, the resume creates a hidden (i.e. starts with `_`) result. The router splits on that to create the real result. Information about the call could be packed into the hidden result.

### Alternative 3 (similar to the webhook approach)

* Instead of exposing `@resume` in expressions, the resume creates a result. The router splits on that, and doesn't actually save a result itself.
* The result created by resume has category of `Success|Failure` and the router uses `has_category` on the result name.

**Comment by rowanseymour** [comment]
Having slept on this I find myself leaning toward the `@resume.type` approach. We try to be conservative about adding new things to the context, especially the root of the context, but `@resume` feels like it belongs in there like `@trigger` (there's already `@trigger.type`). 

A wait followed by a router on resume type (we already have an concept of wait type W allows resume types X, Y, Z).. feels like a model that might be useful for other new wait/resume combinations in the future.

**Comment by nicpottier** [comment]
I like adding `@resume` I think.

Note that for the call, we really need `answered`, `busy`, `no-answer' and `failed` as distinct possible outcomes.

I'm struggling a lot on what the wait should be called. `redirect` feels problematic because it isn't a final redirection, it returns, but maybe that's being pedantic. `call` is maybe clearest but gets confusing because we use `call_classifier` etc, in other places. Nexmo uses `connect` but that's really generic.. `conference`? `dial`?

**Comment by rowanseymour** [comment]
The other reason I talked myself out of `call` is that you can imagine one day the current IVR call being exposed in expressions.. like `@call.duration` or something similar.

That's a good point about there being more than two states for result of the redirection.. so maybe there shouldn't be different resume types here but one new type with a property that we split on.

**Comment by nicpottier** [comment]
Ya, I was originally thinking one resume type with extra fields.

**Comment by rowanseymour** [comment]
So.. after trying to implement this in https://github.com/nyaruka/goflow/pull/998 I've given up on the idea that this is some sort of generic URN redirection thing, and decided it was a lot clearer to just let this be a phone thing. So I've ended up using the `dial` naming `status` terminology from TwiML.

 * A `dial` wait type with a `phone` property (like a `msg` wait)
 * A `dial_wait` event created when that thing begins (like a `msg_wait` event)
 * A `dial` resume type which contains a `dial` object with `status` (`answered`|`no_answer`|`busy`|`failed`) and `duration` (`int`) properties
 * A `dial_ended` event created when the resume ends the wait (like a `msg_received` event)

It's a little odd using `dial` like a noun and I don't love `dial_ended` but it all works..

**Comment by ericnewcomer** [comment]
I think `dial` works just fine. I actually prefer it to both `call` and `redirect`.
