### ISSUE TITLE
Mixpanel Integration

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#514]
It would be amazing to be able to push out all events to Mixpanel just with a global setting. Presently I have to create individual items on each event with a web hook, and it's not easily maintained.

**Comment by nicpottier** [comment]
We've dabbled with the idea of doing say a Segment.io integration, since everybody likes their own flavor of tool for reporting this stuff.

How would you envision this working in a flow? That there is a custom action like "Log Event" where you enter in the event tag (ex "Started Registration")? We would then log using the contact UUID?

**Comment by ericries** [comment]
We already have a Mixpanel_firehose ready to go, we just need help wiring it up to be called as a webhook from RP
