### ISSUE TITLE
Filter contacts in API by multiple groups

### ISSUE THREAD

**Issue by dpoirier** [rapidpro/rapidpro#541]
We'd like to be able to use the Contacts API to retrieve all contacts in any of a list of groups.

For example, maybe add a "groups" parameter to the contacts list API which takes a comma-separated list of group UUIDs.  Contacts are returned if they are in any of the groups.

Having this functionality would make contact syncing more efficient in TracPro, which currently has to make multiple queries to get the contacts in all the groups that it's interested in.

Does this sound like a useful addition to the API? Does the proposed form of the new feature sound reasonable?

If this sounds acceptable and once we agree on how exactly it should work, I can submit a pull request to add it.

**Comment by nicpottier** [comment]
Hi Dan.. this was removed in API v2 because it's impossible for us to provide that API at scale while still being performant. Once you get to millions of contacts in a single group, then the union across the related tables and sorting on modified becomes too expensive since it can't be pre-calculated.

While the v2 API is a bit more work for clients, the changes made were done so that we can make guarantees we can always keep regardless of scale and some things just aren't possible to optimize for such as this.

@rowanseymour may have some more comments and ideas here though.

**Comment by rowanseymour** [comment]
Not much more to add other than you may want to consider syncing _all_ contact changes to TracPro - the contact endpoint returns contacts as they are modified so it's possible to mirror the RapidPro contact state in an external system. This is what we do in [CasePro](https://github.com/rapidpro/casepro) and it lets us implement CasePro's particular access patterns more efficiently that what can provide over the RapidPro API.

**Comment by dpoirier** [comment]
Yes, we might switch back to syncing by modification time. We were trying to resolve a sync problem and started fetching all the contacts for the groups we were interested in each time we synced.
