### ISSUE TITLE
Set preferred contact method (Twitter, SMS, IVR) on contacts.

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#57]
IVR/SMS preference selection (similar to language preference function)

**Comment by mberg** [comment]
Can we add email?

**Comment by ericnewcomer** [comment]
This issue is for setting the preferred channel amongst existing channel
types. There currently isn't an email channel.

I think the more interesting question is, is this for setting a preferred
channel instance or channel type?

Seems we may want both, but it could be confusing to have more than one.

**Comment by ericnewcomer** [comment]
There is now a preferred channel action.
