### ISSUE TITLE
USSD starcode shortcuts

### ISSUE THREAD

**Issue by nullcode** [rapidpro/rapidpro#593]
I've been researching how could we implement USSD shortcuts for RapidPro. (Shortcuts are what we call immediate answers to menu options by dialing the USSD number with the answers given eg: `*111*123#`). 
The general idea is to implement it in a similar fashion as to how "Split by message form w/delimiter" works.

First let's take a look how USSD codes are formed (by the specification of 3GPP TS 22.090):
`*111#` , where:
`*` is the starting character 
`#` is the ending character
Between these you can have numbers followed by optional * character and _"* followed by any number of any characters" from 3GPP TS 22.090_

Now, the specification doesn't say anything about shorcuts so it's left for the USSD gateways to implement them. By that I mean you will want to have a USSD shortcode that you type in followed by some extra characters and eventually terminated by `#`. If the gateway supports that it will find the appropriate shortcode to connect with the application and relay the whole code to the application.
eg:
`*111*2313#` , where
`*` is the starting character 
`111` is the USSD shortcode
`*` is an optional delimiter
`2313` is the optional extra set of numbers
`#` is the ending character

This example would be one way to do it. Here the number 2313 would be split and every number would represent a menu option: 2 then 3 then 1 then 3. _(This example is actually how InfoBip USSD gateway implements USSD shortcuts or as they call it -- menu-skipping.)_

One other way would be to use `*`s as delimiters, so we could potentially have two digit numbers (fairly uncommon in USSD menus though):
`*111*2*3*11*3#`
It all boils down to how gateways are interpreting this code and relay it to the application.

A real example would be to use a VUMI USSD shortcode eg: `*120*8864*1111#` that would connect to our application _(it would trigger a flow in RapidPro)_. The question here is if we can still add extra characters here and they would be visible in our application (eg: `*120*8864*1111*2313#` would trigger the flow and take 2, 3, 1, 3 as answers to menus options.
@smn Can you confirm that this is currently working in VUMI/Junebug ?

When the full USSD code arrives to our application, we will need to split it and take the shortcode to trigger the flow and determine the extra characters and process them as answers to menus.

This is how I think RapidPro would work it out from here:
1. Flow is triggered and the extra set of numbers would be called with the flow
2. Each number would be an answer to a menu starting from the entry point.
3. a) If the number given is a valid answer it would go down the flow and process the next answer (if any).
3. b) If the number given is invalid the Other branch would be triggered and the flow could trigger the ruleset again (now sending the message out).
4. a) If there are no numbers left and the flow still has not been ended, the flow would continue from there and send menus out to the user.
4. b) If there are no more menus left the flow would be ended, session would be terminated, answers would be saved.

Implementation considerations:
- The USSD menu rulesets could have the new logic hidden from the user (so the User doesn't need to select which field is this ruleset answering or what delimiter are you using -- Split by message form)
- The delimiters could be automatically detected and options could be automatically processed.
- If shortcuts would be used, menus wouldn't be sent out (until there are shortcut options left or valid options only)

These are my preliminary plans here, any type of feedback, comment is welcome and validation by @nicpottier @ericnewcomer @rowanseymour would be needed before I start implementing it. Thanks

**Comment by nicpottier** [comment]
We've been chatting about this a bit and I don't think it really makes sense to try to do so much magic in inferring the possible paths and automatically passing through menus etc.. I'll admit that one reason is that seems pretty complicated to implement and I'm a bit concerned about the implications to the flow engine for other cases, but more importantly I don't think we can generically do the right thing here, there is just too much inference taking place.

For example, while at first glance it seems that swallowing menus that are "skipped" makes sense, what about other actions, such as messages or contact updates etc.. Are those skipped as well? Either answer begs the question as to whether that is the right or expected answer for a flow author.

It also seems that shortcutting is likely something that authors would want the option of enabling, not only per org but also per flow and perhaps even per branches in a flow, the configuration of all that sounds like it would get complicated very quickly.

What if instead we treat these as triggers, which basically maps to how these are used in USSD anyways? That way authors can have full control that this longer sequence triggers this flow with this state. It is a bit more work for flow authors, but since these kinds of shortcuts are things that users have to learn anyways it seems they won't be super common anyways. But it then gives flow authors full control as to how to handle various paths and to offer custom dialogs and paths for them. Perhaps most importantly it fits the current paradigm a lot closer than trying to do some kind of automagic menu execution etc..

**Comment by smn** [comment]
@nullcode we do no inference on the USSD code, we treat it like an opaque identifier that is used for routing only. Other than an entry point it doesn't map to any logic on the application side.

The reason we never implemented it in Vumi Go is because we feared it be fairly complex for the end user to reason about, and it makes fairly big assumptions about the behaviour and immutability of the underlying system. Once a *1*1*# could was out in the wild and used it would need to remain largely immutable in terms of flow control because any change in the flow steps would break or at least potentially change that number's behaviour away from what the user wanted or expected.

For us the benefits never came close to the level of effort required to do this well and so we didn't do it.

What we did implement was the ability to resume timed out sessions, there are signals that an application developer can hook into which can trigger custom logic. By default it would put the user back where they left off if they timed out but other strategies are things like sending an SMS informing the user that they could dial in to complete the session or prompting the user whether they would want to resume or start from the beginning.

If some of the thinking behind menu skipping is to allow people to go further in menus then we partly answered that by being able to resume sessions that timed out. Again, this also enables a terrible UX because designing flows with the expectation of needing 3 timeouts to complete it silly.

**Comment by nullcode** [comment]
@nicpottier so in theory if you have `n` number of menus in a flow the author would need to create `n` flows with `n` triggers if he wanted to prepare for all possibilities? How are answers saved with this approach ? Say I have a shortcut to answer the first menu that asks your gender how would that answer make it to the system? 


@smn  I agree with the immutability problem and that's a nice feature that you can resume timed out sessions (maybe we could incorporate this into RapidPro somehow?) 
My original question was rather directed at the USSD code being routed the proper way when you use extra characters in it and it is still preserved as is in the application.
For eg: `*120*8864*1111#` is the USSD Code you get in Vumi GO and you set it up to call a RapidPro channel. The question is, if a person calls `*120*8864*1111*2313#` instead, does it still get routed to the RP channel and does it show up as the `from_addr` ?

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
