### ISSUE TITLE
No Email Verification During Signup

### ISSUE THREAD

**Issue by mracter** [rapidpro/rapidpro#614]
The account registration process does not require the registree to verify ownership of the email account entered. As the application disallows using the same email address to register and account on the same RapidPro instance and does not namespace users under organisations, this could result in malicious parties blocking the registration of legitimate staff by fraudulently signing up with staff email addresses.

The primary implication of this vulnerability is Denial of Access for future legitimate users of the RapidPro application, whose email addresses were obtained by threat actors.

This issue was found in RapidPro v3.0.136p4 during a routine security assessment.

**Comment by nicpottier** [comment]
Thanks for the report!

This is by design in that we view the advantage of lack of friction in signing up greater than the risk of having email addresses taken over this way. Password resets are done via email so there's no real way for an attacker to permanently claim an email address and prevent the real owner from taking it over.
