### ISSUE TITLE
Fail to send flow to more than one contact.

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#617]
The below error is returned when I try to send a flow to more than one contact or some group:

`TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'`

 This happens because `priority` in `push_task` comes `None`, could you say if this a bug? If yes, do you already have an update to resolve that?

**Comment by nicpottier** [comment]
Ya, this was introduced in: 
  https://github.com/rapidpro/rapidpro/pull/602

And fixed with:
  https://github.com/nyaruka/rapidpro/commit/ca56640269fa2585ee938b50d7e26e4c88cddd98

We haven't merged because our branch has some crazy migrations in it in support of Twitter ids and we want to finish that first.

CC: @erikh360 just because that's a tricky lambda bug!

**Comment by nicpottier** [comment]
I'll see about applying just that one fix to /rapidpro now

**Comment by nicpottier** [comment]
Fixed in https://github.com/rapidpro/rapidpro/commit/ab3f86a9fc8f092c5ea2f0ce8cf3253dceed72e9
