### ISSUE TITLE
Duplicating contacts when starting flows to Facebook opt-in users

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#633]
Contacts are being duplicated when calling `api/v2/flow_starts.json` with `user_ref` URN, this is the request body:
```
{
    "flow": "262f439f-b813-4592-8eb6-c34a81e5fc42",
    "urns": ["facebook:ref:wc_order_59b7f08392cb2"]
}
```

The flow is started, but a new contact is created with empty data. The other bug is that when you respond to that flow and you already have a registered contact for your Facebook account, the message comes into RapidPRO as your Facebook user.

**Comment by nicpottier** [comment]
Huh that's an interesting use case to be calling into the API with a facebook ref. In any case happy to take a PR to fix this.

**Comment by johncordeiro** [comment]
Great @nicpottier, I'll send a PR to fix the flow_start for Facebook ref. Besides that, after triggering a flow by "referrer id" (using Facebook Checkbox) to an existing Facebook contact, do you know a way of link the new "user_ref" with the existing contact?

**Comment by nicpottier** [comment]
So looking at the how things have worked up to now, it looks like referrals were used to trigger flows and then based on the result of sending a message we would get the real facebook id and then remap from there. As far as I know that's the only way to turn a referral id to a real id, do you understand that differently?

So in your case this is a contact that already exists that is coming in via a referral? 

It is pretty tricky because we have to create the original contact when we get the referral id, but we may find out after sending a message to that that the contact already exists.. so we might need to do something fancier in the Facebook send to deal with that case and somehow join the contacts.

**Comment by nicpottier** [comment]
I believe this contact merging was addressed.
