### ISSUE TITLE
Feature Request: Web based Flows

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#695]
I would like to be able to use Rapid Pro's flow creation tool to ask questions, generate responses, run webhooks, etc.  on a URL that I can direct contacts to.

For example, consider typeform, which asks a single question at a time, has logic based on the answers to questions, etc. https://www.typeform.com/examples/

This would enable an entirely new set of use cases around building web based surveys, intake forms, workflows, etc.

Essentially, it is similar to the survey/surveyor functionality but instead of deployed on an android smartphone, it's deployed at a URL.

**Comment by cromulus** [comment]
Had a thought, could be a bit of a refactor of the "simulator".

I may have some bandwidth to take a crack at this early next year. Would this be something that the core team would be interested in potentially merging?

My thoughts are that it is somewhat of a mix between the surveyor and the simulator, except instead of a random phone number being generated, we allow optional variables (uuid, urn, etc) passed in through GET params/url path that can establish the contact's identity or ask for their urn in the questions, if so desired, otherwise the contact remains anonymous.

**Comment by nicpottier** [comment]
Definitely encourage anybody wanting to play with this to do so, but we do
not envision this as part of RapidPro. Everything needed should be
available via APIs or by using an external channel but we don't want to
expand the core product to be maintaining a web widget or the like. (that
can easily love outside RapidPro)

On Dec 10, 2017 10:58 AM, "Bill Cromie" <notifications@github.com> wrote:

Had a thought, could be a bit of a refactor of the "simulator".

I may have some bandwidth to take a crack at this early next year. Would
this be something that the core team would be interested in potentially
merging?

My thoughts are that it is somewhat of a mix between the surveyor and the
simulator, except instead of a random phone number being generated, we
allow optional variables (uuid, urn, etc) passed in through GET params/url
path that can establish the contact's identity or ask for their urn in the
questions, if so desired, otherwise the contact remains anonymous.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rapidpro/rapidpro/issues/695#issuecomment-350558026>,
or mute the thread

**Comment by cromulus** [comment]
If I'm reading this correctly, the way to implement this would be through creating a new channel, as opposed to a feature built into the core of rapidpro. Interesting.

What do you think about a channel that effectively exposes an API, that then there's a chunk of JS you can paste on to a page, configure it with the uuid of the flow, and potentially pass in variables and it outputs the question flow? 

I'll take a look at some of the other channels to see how they are implemented.

**Comment by nicpottier** [comment]
Yep, that's correct, there's nothing really different to a web chat box and everything needed should already exist in the RapidPro world. It could simply be an external channel with a UUID URN type and communicate incoming and outgoing messages using the endpoints you get when adding an external channel.

That decouples the development of that web-widget from RapidPro and allows it to move as fast (or slow) as it needs to. Could see a generic web-chat-widget doodad being generically useful for other projects other than RapidPro for that matter.

**Comment by ewheeler** [comment]
we implemented something similar a while back but it has not been maintained:

https://github.com/rapidpro/ureport-web-participation

**Comment by ewheeler** [comment]
see also https://github.com/rapidpro/rapidpro/issues/582

**Comment by nicpottier** [comment]
Closing, don't think this belongs in RapidPro, another project can certainly add this using an external channel.
