### ISSUE TITLE
Timeout category in Call Flows

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#728]
I was wondering how to handle better timeouts in Call Flows to avoid endless loops of pound responses or empty callbacks on TwiML. Do you think that's a good idea implement the `timeout` category in Call Flows, like in `Text Messaging` one?

**Comment by johncordeiro** [comment]
@nicpottier any thoughts on this?

**Comment by nicpottier** [comment]
I don't think this is really the same as a timeout is it? Seems it is more similar to having someone continually send back an invalid response in a messaging flow, which isn't dealt with in any special way.

That said, I think the bigger problem here is just that an IVR call can go on forever and there's essentially no way to say in a flow that this call should never go on for more than 30 minutes or whatever to deal with this kind of abuse.

Essentially then that would be a configuration on a flow for a max duration. Not sure we need / want that to be something that is exposed in a flow itself, more like something where the call is terminated after that duration.

Thoughts @ericnewcomer  @dodobas ?

**Comment by ericnewcomer** [comment]
Agree that as implemented the solution seems to point to a max duration for a call -- something that we likely ought to have regardless. However, this is more because of how we deal with timeouts on IVR calls in the product -- if, we currently generate a callback that looks like no input followed by a terminal keypress. 

I see a couple different ways forward:

1) Leave gather timeouts hardcoded as they are with callbacks of just terminal keypress, but implement a max duration

2) Allow the user to specify the timeout period as they do in message flows, but with IVR appropriate values (30s, 60s, etc), and generate a No Response exit just as we do for text messages.

While it is higher effort, I think giving the user control over the gather timeout is worthy of consideration.

**Comment by johncordeiro** [comment]
<img width="400" alt="screen shot 2018-06-26 at 12 07 39 pm" src="https://user-images.githubusercontent.com/6073075/41921587-940310a2-7939-11e8-8ee9-c685fa85b843.png">

PR welcome here in Call Flows?

**Comment by nicpottier** [comment]
I don't think we want to introduce any new changes to call flows until we ship the new engine, at that point we will be giving call flows a lot more attention and addressing cases like this. Adding more things to the current implementation just delays us launching that one.
