### ISSUE TITLE
Send Message Broadcast to Group Disabled

### ISSUE THREAD

**Issue by mattcrum** [rapidpro/rapidpro#745]
I noticed in PR #730 the broadcast to groups function was disabled. We use the Send Message button to broadcast a message to groups fairly frequently. If you don't mind, what's the reasoning for removing it? To have to create a new flow with one message in it and trigger the flow on a group is a bit less intuitive for our users, especially since they've learned this other way.  It adds a lot more steps to send, but also to remove the flow that will never be used again since it's just a single broadcast. It's definitely tripped up some of our users.
Thanks!

**Comment by nicpottier** [comment]
Ya, there's a variety of reasons we removed that, some due to people sending multiple broadcasts due to not having great feedback when creating broadcasts to large groups that things were underway as well as overall wanting to really push users towards flows, because in the end that's where the real benefit comes from.

So we actually view the need to create a flow to do a broadcast as a plus, it is a baby step towards familiarity with flows for users and introduces them to the featureset that really makes the platform special.

**Comment by mattcrum** [comment]
@nicpottier what about scheduled messaging to groups? We've used this quite a bit in the past. Are we left to create individual triggers and flows for each message? During the ebola outbreak for example, we had over 50 messages scheduled and really appreciated that feature. It'd be really unfortunate for us to have to make 20 triggers and 20 flows to schedule messages.
