### ISSUE TITLE
Querying created_on with time should yield error

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#808]
Currently in my tests, this returned all contacts:

created_on < "2017-08-09 18:38:24.469581+00:00"

Would expect none and an error for the user since time isn't supported.

**Comment by nicpottier** [comment]
@dodobas what's going on here?

**Comment by dodobas** [comment]
let's see

**Comment by rowanseymour** [comment]
I'm fairly sure our 3 search implementations don't support full date times, i.e.

`created_on > "2017-08-09"` is calculated as `created_on >= "2017-08-10T00:00:00Z"`
`created_on >= "2017-08-09"` is calculated as `created_on >= "2017-08-09T00:00:00Z"`
`created_on = "2017-08-09"` is calculated as `created_on >= "2017-08-09T00:00:00Z" AND created_on < "2017-08-10T00:00:00Z"` etc

My preference would be to keep it that way and give users better error messages when we can't parse a search query.

**Comment by dodobas** [comment]
`str_to_datetime` (https://github.com/rapidpro/rapidpro/blob/master/temba/utils/dates.py#L24) can't parse that as an valid ISO8601 date
and then we try to be smart and eventually parse that as `2018-09-08 18:38:24.469581+00:00` ... so that's why it returns all contacts...

**Comment by dodobas** [comment]
the year was 'upgraded' to current year :)

**Comment by dodobas** [comment]
this specific case is a valid ISO 8601 representation, as stated `"ISO 8601:2004(E)". ISO. 2004-12-01. 4.3.2 NOTE: By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard."` (https://en.wikipedia.org/wiki/ISO_8601#cite_note-30)

we could add support for it by updating the regex - https://github.com/nyaruka/rapidpro/blob/d0bb9fa8502cdde80ea658bee78ad96b76ccb5f1/temba/utils/dates.py#L14-L14

however, the original issue occurs because we are too optimistic when parsing dates, multiple combinations are tested (https://github.com/nyaruka/rapidpro/blob/d0bb9fa8502cdde80ea658bee78ad96b76ccb5f1/temba/utils/dates.py#L69-L76) and eventually one of those will return a _valid_ date. 

for example, the combination of a string `2017-01-12 11:12:34` and regex `DD_MM_YYYY = regex.compile(r"\b([0-9]{1,2})[-.\\/_ ]([0-9]{1,2})[-.\\/_ ]([0-9]{4}|[0-9]{2})\b")` gets parsed as `01-12 11` and converted to `2011-12-01` which is not what we want, i think :)

Maybe we could also remove `<space>` char from the regex ? and check if there are any dynamic groups that use <space> when filtering date fields.

Regarding the issue of returning error when date cannot be parsed, we could add a simple length check  `6<= len <=10` (11-1-1, 2011-01-01) in the `str_to_datetime` function to make it fail if the string in not a FULL_ISO8601_REGEX. this would raise a  SearchException( in the query parser `f"Unable to parse the date '{self.value}'"` ?
After the change there is about 10~ish tests that fail

**Comment by rowanseymour** [comment]
Hmm tricky. First thing that sucks here is that we have to maintain two versions of query parsing and evaluation (goflow and RP). Long term I wonder if we can lean on mailroom to do search evaluation? Short term we need to make sure we keep goflow and RP's query parsing and evaluation in sync.

Am I right in saying we don't have to worry about spaces in the case of query parsing because the righthand side of any condition can't have spaces? I.e. `age = 2017-01-12 11:12:34` would be parsed as `age = 2017-01-12 AND name = 11:12:34`

Doesn't look like `str_to_datetime` gives us a good way of saying "parse this as a date only". Seems like we need to add `str_to_date` ?

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2453
