### ISSUE TITLE
Option for sending messages with a few second delay

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#875]
We've discussed this at times in the past but wanted to have an issue to track and discuss this feature oft requested customers. The gist here is they want to appear more human by not replying back faster than somebody can type.

Other considerations would include typing notification on channels that support it.

**Comment by nicpottier** [comment]
This also comes up when people are trying to add additional delays to SMS channels to try to insure SMS order. 

We currently automatically add 3 second delays when sending back to back messages to contacts to try to help here, but that's still no guarantee (no value will be really):
  https://github.com/nyaruka/courier/blob/master/queue/queue.go#L154

This does come up a lot as a feature request though, both for the "fake a human" case and the "try to ensure ordering" cases.

I think we have two ways we could go here:
 1. Add an option to a reply action which is a "pause before sending"
 2. Have lower limits on our timeouts on rulesets, our lowest timeout is currently one minute, could make this something shorter

Both of these have some challenges, both in implementation and in what behaviors should be.

For option 1) of allowing an pause before send:
 1. The user may interpret this as a pause in the flow, which it isn't, it would only take effect when sending by courier, and that may be confusing
 2. For larger pauses, say 30 seconds, behavior can get awful bizarre to a contact. IE, imagine a user starts a flow with a keyword, gets the first response with a second queued to send in 30 seconds, but before receiving the second response, replies with another trigger which starts then in another flow. It sure would be nice if that second queued message is not sent in that case, but that has some complicated implications. (courier needs a concept of 'cancelling' pending messages for a contact, we need to delete that message from the contact message history, etc..) Note this exists today with the built in 3 second pause but with that short a pause it doesn't (or at least hasn't to our knowledge) led to confusing interactions. This mostly becomes an issue when you start doing > 5 second pauses.

So I think option 2) is really the more accurate representation of what is happening to the user. It also gives the user the ability to choose to do something different if the user DOES reply before the pause is complete through mechanisms that already exist (rulesets, etc..) Challenges here are:
 1. These are considered "timeouts" in flows. Timeouts are checked every minute and treated as fairly low priority by the system (IE, priority goes to handling incoming messages but we do our best to deal with these ASAP)
 2. If we allowed much shorter timeouts (5 seconds) then we have to check them more often. That's probably not the end of the world as total work is probably about the same, but there is perhaps a problem in implying an accuracy of "5 seconds" which is a contract we may find hard to honor at all times. We may need to treat timeouts as the same priority as message handling in that case.
 3. A timeout is a resumption of a flow, and while that is now pretty darn fast in mailroom, it is also not a super cheap action, involves loading up the session, firing the action to the engine and writing new updated sessions and runs. If someone is doing this for a flow being started for a few million contacts that's an awful lot of events generated that we need to deal with. (mailroom is worlds better about this but still..)
 4. We don't do any loop detection for infinite timeouts (IE, having a timeout loop back to the original message). That has occasionally caused a message to be sent every minute to someone when a flow is configured as such, doing that every 5 seconds would be 12 times more annoying. We may need to disallow that kind of routing in the editor before opening that as a possibility.
 5. From a flow building perspective adding a ruleset with a timeout between every set of messages may be pretty annoying. I think I fall on the side of "a bit more work for editors to design a flow good for contacts is ok" but it deserves mentioning. That "pain" may also make people use this only when absolutely necessary which may be better for us.

I think right now neither of these feel quite right which is why we aren't moving on this just yet.

**Comment by nicpottier** [comment]
Another thought here is to make this a "checkbox" on a channel that essentially introduces a delay of ~5s when sending reply messages. That would be relatively easy to implement and maybe would satisfy most use cases where people just want their bot to appear more human. Having it be a vague checkbox and at the channel level also means it makes very few promises around flow execution, handling etc..

**Comment by rasoro** [comment]
Back to this issue, we've been discussing proposals for this feature. For this, we take into consideration what has already been said here.

we think to following suggestions:

![miro](https://user-images.githubusercontent.com/75167930/125512023-cc9660bf-8576-4f6f-90a4-8c148b38068f.png)

1. A new option to be enabled on the message sending node with delay time options that would send the message after this wait. To make this possible we imagine that it will be necessary to save the delay time in the definition of the flow, some change in the mailroom to send this message delay metadata for the courier to apply this delay.

![delayed_send_message](https://user-images.githubusercontent.com/75167930/125512135-3e19d69b-7e0c-4cc8-83f8-c0a6e6be9dca.png)

2. More options of time less than 1 minute in wait for response, which would result in tick time changes in the mailroom timeout cron, and make these additional options available in the floweditor

![ss1](https://user-images.githubusercontent.com/75167930/125512480-699a6c92-c190-41d0-ab3b-17f95070a004.png)


3. a new delay node where a time would be defined that would pause the flow execution and after the wait interval it would return an execution to the next node.

So with that we imagine the following problem. If the user keeps sending a message, would the system move forward or would it be waiting and accumulating?

e.g:

bot: Tell me why you don't want to help?

user: because i
user: I'm not feeling well today
user: and I don't know if I could help

the user sends 3 messages, in the first one he goes through the Wait For Response and accumulates the next ones.

Or, if you define 3 send message nodes in the flow and then when the user sends 3 messages you treat it as 3 different wait for response, the flow would go wild and we'll have the same problem.

can we discuss how to work around this problem of accumulation of messages in the suggestions presented?

**Comment by nicpottier** [comment]
You didn't list the option which I think is best, which is a setting either on the workspace or the channel to introduce jitter. This really can't be implemented as timeouts, so that option should just be removed. So the only real question is whether it is a per-message setting or a workspace or channel setting. It feels like a pain for users to have to set this on every outgoing message, they probably want their bot to always "feel" human, so having it on the workspace or channel seems like the right thing to me.

**Comment by ericnewcomer** [comment]
I much prefer the option of it being at the channel level and having the timing be non-user selected. ie, 
  - [x] Delay messages to appear more human

The channels could conceivable implement typing presence if supported as well.

**Comment by rasoro** [comment]
> You didn't list the option which I think is best, which is a setting either on the workspace or the channel to introduce jitter. This really can't be implemented as timeouts, so that option should just be removed. So the only real question is whether it is a per-message setting or a workspace or channel setting. It feels like a pain for users to have to set this on every outgoing message, they probably want their bot to always "feel" human, so having it on the workspace or channel seems like the right thing to me.

do you think we can achieve this by receiving this configuration in the channel or workspace in place of these 3 seconds of this line? https://github.com/nyaruka/courier/blob/master/queue/queue.go#L154

**Comment by rasoro** [comment]
and about this problem of user response accumulation, what do you think?

**Comment by ericnewcomer** [comment]
I don't see this as related to response accumulation, and if that was something we wanted to do (which I doubt), it would probably need to be handled in a similar fashion (stitching inbound messages in a window to a single message, etc). But ya, that's a no from me.

**Comment by nicpottier** [comment]
To be clear, any response will be handled by the next wait. Since this is not implementing things as a way, then I think things work just fine. If it *was* a wait to do a 3 second delay or whatever then it would be super annoying both from a structure of the flow and also because you'd have to have one ruleset that is just the wait then another that has the actual rules and the wait would absorb that first message in that case.

Note that even random waits couldn't cause out of order messaging as Courier sends from a queue of messages per contact. This would just be pushing a "send contact message" task with a future timestamp when sending.

**Comment by rasoro** [comment]
I partially agree with your opinion in this thread.
To bring more context to this, I would like to share the following situation.
Some users when creating flows want a time to wait for a response of less than 1 minute. For example, when building a flow sometimes the user needs to accumulate responses and go to the next node waiting less than 1 minute after the user finishes responding, waiting more than 1 minute looks strange to the user.
To exemplify, imagine the following flow as an example of the accumulation of responses.

![example_accumulate](https://user-images.githubusercontent.com/75167930/126163842-21a8c5da-ddfe-4be5-96c4-99933465b4f1.png)

The solution via channel does not cover situations like that. The user does not want to apply the delay messages for all messages on a specific channel. When contact is talking with the chatbot, and if is necessary to apply the delay, this feature provides this, and after that, the normal flow to send messages continues normally.

**Comment by ericnewcomer** [comment]
Accumulating inbound messages is a different issue altogether from delaying outbound messages to appear more human. Personally, I don't think it's a good idea to change inbound handling in this way, but it should be a separate issue if you want to discuss it.

**Comment by rasoro** [comment]
makes sense so I'm moving to a new issue. #1535

**Comment by ericnewcomer** [comment]
So do we have consensus around an option at the channel level as the direction for adding delays for outbound messages? Can I get a show of thumbs?

**Comment by textitdone4you** [comment]
Just wanted to bump this "enhancement" and see if it was on the roadmap. I've been following this thread for a few years and would love to see the delay feature.  Thanks

I've also noticed that messages are more likely to arrive out of order in French (not the default language - have not seen it happen in English) on facebook messenger, but not on WhatsApp.

**Comment by rudigiesler** [comment]
For out of order messages, an idea we've had in the past is to use status updates to ensure message ordering. So you send the first message, and then wait for the appropriate status update before sending the next one. This is done on a per-contact basis.

This might be difficult to implement across a wide range of channels, as different status updates mean different things, so maybe a delay is a simpler option to implement, but it will guarantee message order, where a delay will not.

**Comment by ericnewcomer** [comment]
This is an interesting idea but SMS channels do not reliably provide status across the globe.

**Comment by ericnewcomer** [comment]
Moved to: https://github.com/nyaruka/rapidpro/discussions/4222

**Comment by awesomesimba** [comment]
Hello, I have been following up the conversation on how to set an option of sending messages with few delays , Currently i have hosted my project is powered by Nyaruka but the minimum delay timer is 1 Minutes, I want to set below 1 minute to suffice my purpose. 
Am still learning RapidPro can someone help with the way forward to change the time in backend?

**Comment by ericnewcomer** [comment]
This is not configurable below 1 minute because it would 60x the number of tasks monitoring for fires. Additionally, most asking for a delay are looking for message sending to feel more "human". The solution for that is probably somewhere else, Pegasus at the channel level, and has been the source of a lot of debate.
