### ISSUE TITLE
Dependencies should be part of flow definition?

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#880]
@rowanseymour and I were chatting over lunch and it seems like maybe we need dependencies to be part of the `meta` of a flow definition. One concrete example is our use of `has_group` tests for example. This now just takes a simple UUID, so when importing a definition in a new account, we won't be able to reason about what that test is really testing for, or dynamically create that group in order to allow that import to move forward.

So one proposal would be to have a `dependencies` section in our `meta` that essentially contains the dependencies for the flow as calculated by goflow.

```json
"dependencies": { 
  "channels": [
  { 
    "uuid": "21c4ed91-c3d9-4d92-ac9e-7ced24ca7341", 
    "name": "Telegram"
  }],
  "labels": [
  {
    "uuid": "092b5818-50f1-4130-9507-99de17343de7",
    "name": "Error"
  }],
....
....
}
```

**Comment by nicpottier** [comment]
@ericnewcomer thoughts?

**Comment by nicpottier** [comment]
Occurs to me this would also be useful to the flow editor/viewer to be able to display a flow without an org backing it.

**Comment by ericnewcomer** [comment]
Was just going to say that, can see this making flows more standalone. One thing on dependencies is to be aware that these will never be exhaustive since we can resolve to things via expressions. In general though, I not opposed to this idea. UUIDs of channels feels a little odd. So are these meant to be remapped on import of another org as we used to do with RuleSets, etc? Some things can be recreated (labels), while others cannot (channels). Perhaps that is the boundary of whether a flow can be imported?

**Comment by nicpottier** [comment]
Ya, this obviously can't take into account dynamic group addition based on an expression, but everything static, including fields referenced in expressions should be included.

Channels are definitely super weird dependencies but dependencies nonetheless. We will need to figure out how to handle those kinds of imports, I believe the changes @norkans7 just made essentially remove those actions but we should add in warnings for those cases / give a choice to cancel. (real solution is https://github.com/rapidpro/rapidpro/issues/881)

**Comment by norkans7** [comment]
I had a thought that channels should not be in the flow definition, so I agree with #881 instead of the set preferred channel action

They I thought could work is to have scheme and address instead of uuid and name
I think address can be optional but still allow the current use case of set preferred channel and still flexible for one a channel is removed and added the same address.

Not sure if we need an extra thing to make sure you can differentiate like 3 short codes from different operators, so name can be use as last setting

precedence would be scheme, address and then name, the last two are optional

**Comment by rowanseymour** [comment]
One issue we currently have is that asset references in the flow definition may have stale/incorrect names, and moving those to a single location certainly makes it easier to refresh those names. But that would mean rewriting our actions so they don't also have names... they become just UUIDs. It would make the action on its own a little less readable but would remove any ambiguity about which name is considered correct. For example...

```
"dependencies": { 
  "labels": [
    {
      "uuid": "092b5818-50f1-4130-9507-99de17343de7",
      "name": "Spam"
    }
  ],
  ...
}
```

```
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "add_input_labels",
  "labels": ["3f65d88a-95dc-4140-9451-943e94e06fea"]
}
```

**Comment by rowanseymour** [comment]
Tho on further reflection that won't work because actions typically take either concrete or variable asset references, e.g.

```
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "add_input_labels",
  "labels": [
    {
      "uuid": "092b5818-50f1-4130-9507-99de17343de7",
      "name": "Spam"
    },
    {
      "name_match": "Messages from @contact.fields.district"
    }
  ]
}
```

So maybe we continue using asset references as we have throughout the flow definition, and then "_dependencies" (?) is a just the unique set of them. 

Or we just drop the names on concrete references, e.g.

```
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "add_input_labels",
  "labels": [
    {
      "uuid": "092b5818-50f1-4130-9507-99de17343de7"
    },
    {
      "name_match": "Messages from @contact.fields.district"
    }
  ]
}
```

The engine doesn't use these - the assets are fetched and new references created from them to be used in events. Thus the name in the event doesn't always match the name in the action.

**Comment by nicpottier** [comment]
I think I'd probably lean towards just having normal references there, if for no other reason that there's only one type to think about then.

**Comment by rowanseymour** [comment]
Ok I think we're saying...

* Validating a flow in goflow will augment it with a root-level `_dependencies` section, analogous to the `_ui` section.
* When a flow is saved in RP, we first hit a mailroom endpoint to do that validation and add the `_dependencies` section - and then RP can create db dependencies as needed.
* No changes to the engine's running of a flow... it still uses assets
* No changes to the editor... it still uses the assets server - except it probably should clear `_dependencies` so that it doesn't leave the flow in a state that doesn't match what is listed as dependencies. It's not the editor's responsibility to maintain dependencies.

But one missing piece is still how imported flows would be processed. RP can easily inspect the dependencies section of the flow def and go and create new groups, labels etc.. but we would still need to remap the asset reference UUIDs in the flow def to the UUIDs of the newly created groups, labels etc. RP can't do it because it's not going to know about flow structure.

**Comment by nicpottier** [comment]
Eeek, ya that remapping is an ugly one. Is that something like a dependency map that RP can pass in to mailroom / goflow? Then it is up to goflow to remap dependencies according to that map?

**Comment by rowanseymour** [comment]
Alternate approach: RP does a text-level search and replace of the group and label UUIDs.. they're UUIDs.. they're really really unique!

**Comment by nicpottier** [comment]
But what if people are still using RP after the heat death of the universe?

**Comment by rowanseymour** [comment]
10,000 free credits

**Comment by ericnewcomer** [comment]
Should we extend this concept to include attachments? We have a poor story currently for export / import of IVR flows with audio prompts. Perhaps there should be fully qualified urls in this dependency list that can be downloaded and copied on import.

**Comment by rowanseymour** [comment]
We're still switching to absolute URLs throughout the definition right? This would just be a top-level list to make it easier if we wanted to go fetch those files, re-upload them, and then re-write the URLs in the definition?

Validating a flow in goflow will now add `_dependencies` and `_result_names`. Could certainly add `_media` as a list of URLs well.

```
"_ui": {...},
"_dependencies": { 
  "labels": [
    {
      "uuid": "092b5818-50f1-4130-9507-99de17343de7",
      "name": "Spam"
    }
  ],
  ...
},
"_result_names": {
  "Response 1",
  "Webhook 2"
},
"_media": [
  "http://textit.s3.com/uploads/test.jpg",
  "http://textit.s3.com/uploads/test.mp4"
]
```

**Comment by nicpottier** [comment]
Agree on absolute URLs, not sure I understand the need for _media though.
What are we going to use that for?

**Comment by rowanseymour** [comment]
Yeah don't think it's actually needed. "_dependencies" is only needed for the case of things like group and field references in the flow definition that don't have enough additional data to re-create them in the import case.

goflow could provide something similar to `RewriteTemplates`.. `RewriteURLs` (?)

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/goflow/pull/551
