### ISSUE TITLE
Twitter handle field no longer contains twitter handle

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#894]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/82857/54135943-2943cf80-43f1-11e9-9fa4-22fa03a34a9a.png">

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/82857/54135970-352f9180-43f1-11e9-8677-b1c61998e2ff.png">

![image](https://user-images.githubusercontent.com/82857/54135989-4082bd00-43f1-11e9-9ac0-7c56161e3515.png)

Using the expression `@contact.twitter` instead, works fine

**Comment by rowanseymour** [comment]
Can't seem to replicate this.. any chance the contact in question has a Twitter ID but not a Twitter handle ?

**Comment by putorti** [comment]
No, it's me, I have a handle, and we've had multiple users report it. As I said the expression seems to work fine but it seems `Twitter handle` in the drop down does not evaluate correctly.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/82857/54147914-99f6e600-4409-11e9-807e-9277445a73ee.png">

**Comment by rowanseymour** [comment]
So as counter-intuitive as this may sound, that contact might not actually have a Twitter handle URN.

Originally Twitter URNs were just the handle like `twitter:putorti`. Then Twitter changed their API and said we needed to use user ids instead so we introduced a new URN type called **Twitter ID** that looks like `twitterid:23456765432345#putorti`... which would still display the same.

Can you try changing the ruleset to look at Twitter ID

**Comment by putorti** [comment]
Okay so here's what I'm seeing now

<img width="722" alt="image" src="https://user-images.githubusercontent.com/82857/54151034-463bcb00-4410-11e9-87cd-02c750716484.png">

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/82857/54151041-4b991580-4410-11e9-8a72-0879c8c96f91.png">

![image](https://user-images.githubusercontent.com/82857/54151057-5489e700-4410-11e9-8868-143d6d359821.png)

So it seems `@contact.twitter` is, I don't know what, and `@contact.twitterid` is the handle. This certainly changed, not sure if there's documentation on how this should work today, I'll probably have to go check all the Twitter connection flows to make sure they still work.

**Comment by putorti** [comment]
Either way it seems that some adjustments need to be made to the contact field selection if handle is no longer handle.

**Comment by nicpottier** [comment]
This changed eons ago, suspect you are only just noticing it and it isn't for everybody.

The way this works is that Twitter doesn't actually give us the handle when it delivers a message, it only gives us a twitter id. (this changed when Twitter changed their bot platform about a year back) Having a handle is obviously useful though, so we try to sync that id to a handle in an async process, but it isn't guaranteed to ever resolve for various reasons.

As Rowan said, `twitter` is the old URN scheme for pre-bot 2.0 twitter ids, while `twitterid` is the scheme for new ones. We should probably just remove mention of the plain Twitter one entirely since that is never actually used. (I've noted that for @ericnewcomer in the new editor here: https://github.com/nyaruka/floweditor/issues/451)

This all gets a bit more confusing still because the URN can have the handle within it if it has been resolved, we call this the URN "display" and by default that is what you see when you echo out a URN as you are doing. So the twitter id URN is actually `twitterid:123415#your_handle` with the stuff after the `#` being the handle. But again, this is only available if we have successfully tried to resolve the twitter id to a handle. But when you echo `@contact.twitterid` as you are above, you are seeing the display for your URN which is your handle, even though we actually use the numeric ID to communicate with Twitter.

Looks like this is working as expected though so closing.
