### ISSUE TITLE
Purged broadcasts are shown well past the archive date

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#910]
See a bunch of old broadcasts on the contact detail page beyond the archival point. They look to be purged.

Example:
https://app.rapidpro.io/contact/read/8c8a7a9e-0718-42f5-882e-c7cf6e90c6b0/

**Comment by nicpottier** [comment]
So archiver doesn't do anything with broadcasts presently. (msgs have a reference to a broadcast and we did expand purged broadcasts into msgs but no more than that)

Archives do contain a reference to a broadcast id however, which I think kinda points to that perhaps we shouldn't be deleting these.

On rapid we currently have 56M broadcasts which isn't too bad but our relation tracking recipients `msgs_broadcast_recipients` is 632M which is no joke, as is `msgs_broadcast_contacts` which has 714M rows.

Note that mailroom no longer creates broadcasts for big flow starts, they are only created for actual broadcasts initiated by the user manually or "send to other" actions. (the latter could be something if a very active flow has send to other actions) Mailroom also no longer writes to `msgs_broadcast_recipients` and the last row on that table is for a broadcast created in May of 2018 so that table can probably be dropped. 

We could go a bunch of different ways:
 1. Have a celery task that deletes broadcasts older than n days, this would be similar to how we trim channel logs and sessions etc.. The task could easily be made to be smart enough to only delete broadcasts that have no msgs referencing them in case archiver falls behind.
 2. Have archiver start deleting broadcasts instead. This is doable but no simpler than 1.

Both 1 and 2 introduce the oddity that archives reference a broadcast_id that may not be possible to look up. Maybe that is ok because the text of the message is still around and you can use that broadcast id to group messages in an archive to reconstitute the full set of recipients though.

 3. Keep broadcasts forever, but clear out both `contacts` and `recipients` for them. This keeps some semantic meaning around for the id. Downside is we then have weird looking broadcasts around, which is especially weird from an API point of view. Perhaps it is better to have the broadcast not be present at all vs having one with wrong information.

I think I lean towards option 1. It is a bit of an API change but looking at lots we have only two calls to GET broadcasts in the past few weeks so I don't think people are looking at broadcasts much.

@rowanseymour if you are still around, thoughts?

**Comment by nicpottier** [comment]
(note that `msgs_broadcast_recipients` and `msgs_broadcast_contacts` are our 2nd and 3rd largest tables at 121gb and 101gb each) The broadcast table is only 25gb in contrast.

**Comment by rowanseymour** [comment]
I think I like treating broadcasts like other temporal objects - channel logs and sessions. 

One thing to think about is that a broadcast is currently the means by which you're supposed to send messages via the API. You POST to broadcast, get the `id` of the broadcast, but and that point the message ids don't exist, so later on you can use that id to filter on the messages endpoint. Maybe you should allowed to POST to the messages endpoint to send a single message and you immediately get back the id of a message.

**Comment by nicpottier** [comment]
Original issue fixed in https://github.com/nyaruka/rapidpro/commit/7f323bc2c4ff58151f435bfdbbef23dd43ff7e23

Recipients table dropped.

Will add a new issue about deleting old broadcasts which will take care of the contacts M2M being giant.
