### ISSUE TITLE
Date/time arithmetic not working on stored dates

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#917]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/82857/57053146-2e3b3780-6c5a-11e9-9494-b275f3a7d8b0.png">

Seeing `error evaluating @(legacy_add(contact.fields.newseum_date, -time_from_parts(3, 0, 0))): error calling LEGACY_ADD: unable to convert datetime to a number` when trying to add 3 hours to a stored date. Not a problem on a calculated one e.g. `date.now`

**Comment by putorti** [comment]
It seems that +1 or -1 days works fine on stored dates, but hours no longer do.

**Comment by rowanseymour** [comment]
I think the root of the problem here is the legacy > new expression migration. We don't have enough information to figure out if we're supposed to add time to left hand side or replace the time. So as weird as this sounds, you can probably make this work by wrapping the lefthand side in EDATE(), i.e. can you try something like...

```
@(EDATE(contact.newseum_date, 0) - TIME(3, 0, 0))
```

If we can get you onto to the new editor soon, you'll have access to all the [new functions](https://nyaruka.github.io/goflow/expressions.html#functions).

**Comment by putorti** [comment]
Confirmed that this also fails in Textit: https://textit.in/flow/editor/fd51f18e-32ff-481f-b04c-5b444a833765/

**Comment by putorti** [comment]
Also, if there's a new way to write expressions / things changed, then let me know where that documentation is so I can save it and do things properly here on out.

**Comment by rowanseymour** [comment]
@putorti if you're using old editor, you still have to write old expressions and we convert them on the fly to the new syntax - that conversion is the thing I think is going wrong here. We're still alpha testing it, but If we can get you on the latest code soon, then you could author in the new editor and use the [new expression syntax](https://nyaruka.github.io/goflow/expressions.html)

**Comment by nicpottier** [comment]
Addressed in new editor / engine. Closing.
