### ISSUE TITLE
Error dashboard

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#923]
Currently we don't surface errors across channels and modalities well. For example a failed IVR call vs. failed messages on the messages tab vs. error logs in the channels.

Logging this ticket to consider a centralized dashboard so users can easily monitor their channels, messages, and call failures.

**Comment by rowanseymour** [comment]
Could this be extended to flows? There are some legacy behaviors in flows that we'd rather users didn't do but we have no way to automatically migrate to something else, e.g.

- Using `@legacy_extra`
- Relying on the permanence of `@webhook`
- Using `.extra` of a webhook result
- Possibly in future it's not safe to make remove bits of the context because we can't find dynamic access to those parts (see https://github.com/nyaruka/goflow/issues/829).
- Flows with missing dependencies

Maybe it's useful to provide a centralized place in a RP org where these sorts of things are listed. 

- Encourages users to address them
- Allows us to track the extent of these kinds of problems

**Comment by ericnewcomer** [comment]
https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/155984/conversations/25649914615

**Comment by rowanseymour** [comment]
Note that we now have incidents and associated notifications those these have not yet made it into the UI
