### ISSUE TITLE
Detailed flow log in contact history

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#968]
One of the big wins of the new engine is the amount of logging we have around flow runs. We keep flow sessions around for a little while (I think a week) and those contain every little minutia of a flow run, what actions were taken, with which variables etc..

It would be neat to expose this detail on the contact history page. It is an awful lot of information so I don't think we would always show it, but having a way to expand the details of a flow run would be great.

**Comment by rowanseymour** [comment]
Some of the event data is saved to the runs too and we keep those around for 3 months.

**Comment by rowanseymour** [comment]
We need to figure out where we want this data to come from. Currently:

- FlowSession objects have all events for all runs but are only kept for 7 days
- FlowRun objects have only `msg_received` and `msg_created` events but are kept around for 90 days

In an ideal world, S3 would support appending, and every contact would get an S3 file we just keep dumping events into and keep forever.

Next best options:

- We start recording more event types on `FlowRun` and use that as the source of most data displayed in the contact history
- We keep most things as they are, but we add more detail for the last 7 days from events in session blobs

**Comment by rowanseymour** [comment]
Don't disagree with that reasoning but for the sake of discussion let's throw some more options into the mix:

 3. We add a new database table that stores just events by contact. Even non-flow messages could be written here so then contact timelines are always a straight read from this table.. weeeee. Downside is obviously this table gets big quick...doh
 4. We add a new database table (or S3 solution?) to store compressed versions of session blobs that have been deleted. Contact timelines are built from reading sessions from the database, and then if you're looking for older stuff.. extracting from compressed versions (which is probably pretty fast anyway)

Now obviously not suggesting we embark on either of those in the next few weeks for 5.2 but I think it's worth thinking about how the solution we pick now could be improved in the future to provide "more information for more time" 

And I guess those make me lean also toward these being based around sessions blobs instead of runs.

**Comment by nicpottier** [comment]
Yep, agree with all that.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/2545
