### ISSUE TITLE
Start somebody else in flow by id

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#994]
We currently support starting someone else in a flow via UUID, but not id.

Use case here is to allow U-Report to ease the transfer of a contact from using a telephone number to using a whatsapp number. Scenario would be that they send a message to their users like:

`Hi there, you can now use U-Report via WhatsApp, just click here to get started: whatsapp://12065551212?msg=link+12345`

Where `12345` is the contact's id. If the contact sent that message we could then send a verification code to their telephone number to verify ownership.

Could use UUID for this but that's a bit ugly and U-Reporters already are exposed to ids.

**Comment by rowanseymour** [comment]
This might be the point at which our current approach of evaluating an expression and at runtime trying to decide what type of thing is trying to match falls apart because ids and telephone numbers (and maybe group names?) might overlap.

So maybe time to figure out https://github.com/nyaruka/floweditor/issues/627

Or.. just brainstorming... what if `start_session` and `send_broadcast` took contact search queries? Then things like `id = 523562` and `age > 16` work.. but if they were to be dynamic, then they'd be templates and that might get weird.. `id = @contact.id`, `age > @results.age_limit`

**Comment by nicpottier** [comment]
I think dynamic queries are very much going to be a thing soon (they are mostly useless without them) and ya, I actually think search cleanly addresses all these requirements. (though at some performance hit, though not significant for id/uuid searches)

**Comment by nicpottier** [comment]
The use case we know exists is: `ward = @fields.ward`

**Comment by nicpottier** [comment]
Closing, this will be addressed: by https://github.com/rapidpro/rapidpro/issues/953
